var translations = {
    //Menu Items:

       "Metric": { en: "Metric", de: "Metrisch", jp: "メトリック", es: "", fr: "", ar:"" },
       "Imperial": { en: "Imperial", de: "Imperial", jp: "インペリアル", es: "", fr: "", ar:"" },
       "°C": { en: "°C", de: "°C", jp: "°C", es: "°C", fr: "°C", ar:"°C" },
       "°F": { en: "°F", de: "°F", jp: "°F", es: "°F", fr: "°F", ar:"°F" },
       "Analogexplanation": { en: "Enter the Value that should be displayed at 0 V in the field Val.@ 0V and the Value that should be displayed at 5 V in the field Val @5V.The calculated values will be available in the corresponding datasource Analog x Calc", de: "Geben Sie den Wert den Sie bei 0 Volt sehen wollen in das Feld Val.@ 0V, und den Wert den Sie bei 5 Volt sehen wollen in das Feld Val @5V ein.Die Berecheneten Werte werden in den Korrespondierenden Datenquellen Analog x Calc angezeigt.", jp: "「Val.@0V」フィールドに 0V で表示される値を入力し、「Val @5V」フィールドに 5V で表示される値を入力します。電圧データ ＋ ダッシュボード アナログ設定 ＝ 計算値。", es: "", fr: "", ar:"" },
       "ActiveDashboards": { en: "Active Dashboards", de: "Aktive Dashboards", jp: "実行中ダッシュボード", es: "", fr: "", ar:"" },
       "Connect": { en: "Connect", de: "Verbinden", jp: "接続", es: "", fr: "", ar:"" },
       "Disconnect": { en: "Disconnect", de: "Trennen", jp: "切断", es: "", fr: "", ar:"" },
       "GPS Connect": { en: "GPS Connect", de: "GPS Verbinden",  jp: "GPS 接続", es: "", fr: "", ar:"" },
       "GPS Disconnect": { en: "GPS Disconnect", de: "GPS Trennen",  jp: "GPS 切断", es: "", fr: "", ar:"" },
       "Trip Reset": { en: "Trip Reset", de: "Tages KM reset",  jp: "トリップリセット", es: "", fr: "", ar:"" },
       "Quit": { en: "Quit", de: "Beenden", jp: "終了", es: "", fr: "", ar:"" },
       "Shutdown": { en: "Shutdown", de: "Herunterfahren",  jp: "停止", es: "", fr: "", ar:"" },
       "Reboot": { en: "Reboot", de: "Neustart",  jp: "再起動", es: "", fr: "", ar:"" },
       "Language": { en: "Language:", de: "Sprache:",  jp: "言語", es: "Idioma", fr: "Langue", ar:"" },
       "GPS Port": { en: "GPS Port :", de: "GPS Port :",  jp: "GPS ポート", es: "", fr: "", ar:"" },
       "ECU Serial Port": { en: "ECU Serial Port:", de: "ECU Serial Port:",  jp: "ECUシリアルポート", es: "", fr: "", ar:"" },
       "Speed units": { en: "Speed unit:", de: "Geschw. Einh.:",  jp: "速度単位 ", es: "", fr: "", ar:"" },
       "Temp units": { en: "Temp unit:", de: "Temp. Einheit:",  jp: "温度単位", es: "", fr: "", ar:"" },
       "Pressure units": { en: "Pressure unit:", de: "Druck Einheit:",  jp: "圧力単位 ", es: "", fr: "", ar:"" },
       "ECU Selection": { en: "ECU Selection:", de: "ECU Selektion:",  jp: "ECU選択", es: "", fr: "", ar:"" },
       "GoPro Variant": { en: "GoPro Variant:", de: "GoPro Variante:",  jp: "GoProモデル", es: "", fr: "", ar:"" },
       "GoPro Pasword": { en: "GoPro Pasword:", de: "GoPro Paswort:",  jp: "GoProパスワード", es: "", fr: "", ar:"" },
       "Logfile name": { en: "Logfile name:", de: "Log Datei Name",  jp: "- ログファイル名前", es: "", fr: "", ar:"" },
       "Odo": { en: "Odo", de: "KM Stand:",  jp: "走行距離", es: "", fr: "", ar:"" },
       "Trip": { en: "Trip:                  ", de: "Tages KM Zähler:",  jp: "トリップ", es: "", fr: "", ar:"" },
       "Weight": { en: "Weight", de: "Gewicht",  jp: "重量", es: "", fr: "", ar:"" },
       "Serial Status": { en: "Serial Status", de: "",  jp: "シリアルステータス", es: "", fr: "", ar:"" },
       "RPM Smoothing": { en: "RPM Smoothing", de: "Drehzahl Glättung",  jp: "回転メーター円滑補正", es: "", fr: "", ar:"" },
       "Speed Smoothing": { en: "Speed Smoothing", de: "Geschw. Glättung",  jp: "車速メーター円滑補正", es: "", fr: "", ar:"" },
       "Data Logger": { en: "Data Logger", de: "Daten Logger",  jp: "データロガー", es: "", fr: "", ar:"" },
       "GoPro rec": { en: "GoPro rec", de: "GoPro Aufnahme",  jp: "ゴープロ録画", es: "", fr: "", ar:"" },
       "NMEA Logger": { en: "NMEA Logger", de: "NMEA Logger",  jp: "GPS記録計", es: "", fr: "", ar:"" },
       "(decimal)": { en: "        (decimal)", de: "        (dezimal)",  jp: "          (十進法)", es: "", fr: "", ar:"" },
       "base adress": { en: "      base adress", de: "     start Adresse",  jp: "", es: "", fr: "", ar:"" },
       "Main": { en: "Main", de: "Haupt",  jp: "メイン", es: "", fr: "", ar:"" },
       "Dash Sel.": { en: "Dash Sel.", de: "Dash Ausw.",  jp: "ダッシュ選択", es: "", fr: "", ar:"" },
       "Sensehat": { en: "Sensehat", de: "Sensehat",  jp: "拡張", es: "", fr: "", ar:"" },
       "Warn / Gear": { en: "Warn/Gear", de: "Warn/Gang",  jp: "注意/ギア", es: "", fr: "", ar:"" },
       "Speedtab": { en: "Speed", de: "Geschw.",  jp: "速度", es: "", fr: "", ar:"" },
       "Analog": { en: "Analog", de: "Analog",  jp: "アナログ", es: "", fr: "", ar:"" },
       "RPM2": { en: "RPM", de: "Drehzahl",  jp: "RPM", es: "", fr: "", ar:"" },
       "EX Board": { en: "EX Board", de: "EX Board",  jp: "I/O設定", es: "", fr: "", ar:"" },
       "Startup": { en: "Startup", de: "Aufstart",  jp: "起動", es: "", fr: "", ar:"" },
       "Network": { en: "Network", de: "Netzwerk",  jp: "ネットワーク", es: "", fr: "", ar:"" },
       "Accelerometer": { en: "Accelerometer", de: "Beschleunigungssensor",  jp: "-加速度計", es: "", fr: "", ar:"" },
       "Compass": { en: "Compass", de: "Compass",  jp: "方位磁針", es: "", fr: "", ar:"" },
       "Temperature Sensor": { en: "Temperature Sensor", de: "Temperatur Sensor",  jp: "温度センサー", es: "", fr: "", ar:"" },
       "Gyro Sensor": { en: "Gyro Sensor", de: "Gyroskop Sensor",  jp: "ジャイロセンサー", es: "", fr: "", ar:"" },
       "Pressure Sensor": { en: "Pressure Sensor", de: "Druck Sensor",  jp: "圧力センサー", es: "", fr: "", ar:"" },
       "Active Dashboards": { en: "Active Dashboards", de: "Aktive Dashboards",  jp: "ダッシュ表示数", es: "", fr: "", ar:"" },
       "WaterTemp": { en: "Coolant", de: "Kühlmittel",  jp: "水温", es: "", fr: "", ar:"" },
       "Boost": { en: "Boost", de: "Ladedruck",  jp: "ブースト", es: "", fr: "", ar:"" },
       "Revs": { en: "Max RPM", de: "Max U/min",  jp: "回転数", es: "", fr: "", ar:"" },
       "Knock": { en: "Knock", de: "Klopfen",  jp: "ノック", es: "", fr: "", ar:"" },
       "Lamdamultiply": { en: "Lambda multiply", de: "Lambda Multiplikator",  jp: "ラムダ乗算", es: "", fr: "", ar:"" },
       "GearCalculation": { en: "Gear Calculation", de: "Gang Berechnung",  jp: "ギア計算", es: "", fr: "", ar:"" },
       "OFF": { en: "Off", de: "Aus",  jp: "オフ", es: "", fr: "", ar:"" },
       "ON": { en: "On", de: "An",  jp: "オン", es: "", fr: "", ar:"" },
       "Gear": { en: "Gear", de: "Gang",  jp: "ギア", es: "", fr: "", ar:"" },
       "SpeedCorrection": { en: "Speed Correction %", de: "Geschwindigkeits Korrektur %",  jp: "速度補正  %", es: "", fr: "", ar:"" },
       "Analog description": { en: "Enter the Value that should be displayed at 0V in the field Val.@ 0V and the value that should be displayed at 5 V in the field Val @5V. The calculated values will be availabe in the corresponding datasource Analog x Calc", de: "",  jp: "「Val.@0V」フィールドに 0V で表示される値を入力し、「Val @5V」フィールドに 5V で表示される値を入力します。電圧データ ＋ ダッシュボード アナログ設定 ＝ 計算値。", es: "", fr: "", ar:"" },
       "Max RPM": { en: "Max RPM", de: "Max Drehzahl",  jp: "最大RPM", es: "", fr: "", ar:"" },
       "Shift Light": { en: "Shift light", de: "Schalt Blitz",  jp: "シフトライト", es: "", fr: "", ar:"" },
       "Stage": { en: "stage", de: "Stufe",  jp: "ステージ", es: "", fr: "", ar:"" },
       "Voltage divider jumpers": { en: "Voltage divider jumpers", de: "Spannungs Teiler brücke",  jp: "電圧分けジャンパー", es: "", fr: "", ar:"" },
       "Temp In.": { en: "Temp. Sensor", de: "Temp. Sensor",  jp: "温度センサー", es: "", fr: "", ar:"" },
       "Cylinders": { en: "Cylinders", de: "Zylinder",  jp: "- シリンダー", es: "", fr: "", ar:"" },
       "Apply settings": { en: "Apply settings", de: "Einstellungen übernehmen",  jp: "設定を適用する", es: "", fr: "", ar:"" },
       "Apply": { en: "Apply", de: "Übernehmen",  jp: "適用", es: "", fr: "", ar:"" },
       "Startup daemon": { en: "Startup Daemon", de: "Aufstart Daemon",  jp: "コネクション起動", es: "", fr: "", ar:"" },
       "Can Bitrate": { en: "Can Bitrate", de: "Can Bit Rate",  jp: "CAN ビットレート", es: "", fr: "", ar:"" },
       "Main Speed Source": { en: "Main Speed Source", de: "Haupt Geschwindigkeits Quelle",  jp: "車速ソース選択", es: "", fr: "", ar:"" },
       "Warningtext": { en: "WARNING: DO NOT SELECT ANY START UP DAEMON THAT INCLUDES OBD/OBD2 WHILST TUNING YOUR VEHICLE or working with the ECU/PCM. PowerTune Digital users MUST disable OBD polling when tuning or performing any task related to the ECU/PCM by changing the start up daemon above to a NON OBD/OBD2 option and pressing apply, or disconnecting the dash entirely whilst tuning or working with any vehicle electronics. PowerTune Digital assumes no liability for damage to your vehicle/ECU/PCM if polling OBD data at the same time as another device causes an interruption, or for any other reason. Refer to our warranty at https://www.powertunedigital.com/pages/manual", de: "Warnung : Wählen sie keinen Aufstart daemon aus, der OBD/OBD2 enthält, während Sie ihr Fahrzeug tunen, oder mit dem Steuergerät / PCM arbeiten.PowerTune Digital Nutzer MÜSSEN das OBD Polling während Arbeiten mit dem Steuergerät /PCM abschalten.Sie können einfach einen Aufstart daemon wählen der keine OBD/OBD2 option enthält und dann auf übernehmen drücken, oder das Dash komplett während Arbeiten an der Fahrzeug Elektronik abstecken.PowerTune Digital übernimmt keine Verantwortung für schäden an ihrem Fahrzeug / Steuergerät / PCM / Motor when OBD Daten zur selben Zeit mit einem anderen Gerät gepollt werden und dadurch aussetzer verursachen oder aus anderen Gründen Schäden entstehen. Bitte lesen Sie sich unsere Garantie Bedingungen auf https://www.powertunedigital.com/pages/manual durch.",  jp: "警告: 車両のチューニング中または ECU/PCM の操作中は、OBD/OBD2 を含むスタートアップ デーモンを選択しないでください。PowerTune Digital ユーザーは、ECU/PCM の操作中は OBD ポーリングをオフにする必要があります。デーモンを選択するだけで起動できます。 OBD/OBD2 オプションが含まれていないデータを選択して適用を押すか、車両電子機器の作業中にダッシュボードのプラグを完全に抜きます。PowerTune Digital は、OBD データを同時に使用した場合の車両 / コントロール ユニット / PCM / エンジンへの損傷については責任を負いません。他のデバイスにポーリングされる時間が長くなり、他の理由でドロップアウトや損傷が発生する可能性があります。 https://www.powertunedigital.com/pages/manual で保証規約をお読みください。", es: "", fr: "", ar:"" },
       "Scan WIFI": { en: "Scan WIFI", de: "WIFI suchen",  jp: "Wi-Fiスキャン", es: "", fr: "", ar:"" },
       "WIFI Country": { en: "WIFI country", de: "WIFI LAND",  jp: "国別選択", es: "", fr: "", ar:"" },
       "WIFI 1": { en: "WIFI 1", de: "WIFI 1",  jp: "Wi-Fi1", es: "", fr: "", ar:"" },
       "Password 1": { en: "Password 1", de: "Passwort 1",  jp: "パスワード1", es: "", fr: "", ar:"" },
       "Connect WIFI": { en: "Connect WIFI", de: "WIFI Verbinden",  jp: "Wi-Fi接続", es: "", fr: "", ar:"" },
       "Update": { en: "Update", de: "Update",  jp: "アップデート", es: "", fr: "", ar:"" },
       "Restart daemon": { en: "Restart daemon", de: "Daemon Neustart",  jp: "再接続", es: "", fr: "", ar:"" },
       "Update Tracks": { en: "Update tracks", de: "Strecken Update",  jp: "トラック更新", es: "", fr: "", ar:"" },
       "Ethernet IP adress": { en: "Ethernet IP adress", de: "Ethernet IP adresse",  jp: "イーサネットIPアドレス", es: "", fr: "", ar:"" },
       "WLAN IP adress": { en: "WLAN IP adress", de: "WLAN IP adresse",  jp: "WLAN IPアドレス", es: "", fr: "", ar:"" },
       "NOT CONNECTED": { en: "NOT CONNECTED", de: "NICHT VERBUNDEN",  jp: "接続されていません", es: "", fr: "", ar:"" },
       "Damping": { en: "Damping", de: "Dämpfung",  jp: "ダンピング", es: "", fr: "", ar:"" },
       "Version": { en: "Version", de: "Version",  jp: "バージョン", es: "", fr: "", ar:"" },
       "Analog":{ en: "Analog", de: "Analog", jp: "アナログ", es: "", fr: "", ar:"" },
   //Popup submenues

       "Add": { en: "Add", de: "Einfügen",  jp: "入れる", es: "", fr: "", ar:"" },
       "Square": { en: "Square", de: "Quadrat",  jp: "スクエア", es: "", fr: "", ar:"" },
       "Bar": { en: "Bar", de: "Bar",  jp: "ライン", es: "", fr: "", ar:"" },
       "Round": { en: "Round", de: "Rund",  jp: "サークル", es: "", fr: "", ar:"" },
       "Text": { en: "Text", de: "Text",  jp: "文字", es: "", fr: "", ar:"" },
       "Image": { en: "Image", de: "Bild",  jp: "画像", es: "", fr: "", ar:"" },
       "State": { en: "State", de: "Status",  jp: "状態", es: "", fr: "", ar:"" },
       "GIF": { en: "GIF", de: "GIF",  jp: "GIF", es: "", fr: "", ar:"" },
       "Save": { en: "Save", de: "Speichern",  jp: "保存", es: "", fr: "", ar:"" },
       "Colors": { en: "Colors", de: "Farben",  jp: "色", es: "", fr: "", ar:"" },
       "Color": { en: "Color", de: "Farbe",  jp: "色", es: "", fr: "", ar:"" },
       "Clear": { en: "Clear", de: "Löschen",  jp: "整理", es: "", fr: "", ar:"" },
       "Import": { en: "Import", de: "Importieren",  jp: "インポート", es: "", fr: "", ar:"" },
       "Export": { en: "Export", de: "Exportieren",  jp: "エクスポート", es: "", fr: "", ar:"" },
       "Backround": { en: "Backround", de: "Hintergrund",  jp: "背景", es: "", fr: "", ar:"" },
       "Close": { en: "Close", de: "Schliessen",  jp: "閉じる", es: "", fr: "", ar:"" },
       "Load": { en: "Load", de: "Laden",  jp: "ロード", es: "", fr: "", ar:"" },
       "Cancel": { en: "Cancel", de: "Abbruch",  jp: "キャンセル", es: "", fr: "", ar:"" },
       "Style": { en: "style", de: "Stil",  jp: "スタイル", es: "", fr: "", ar:"" },
       "Extra": { en: "Extra", de: "Extra",  jp: "追加", es: "", fr: "", ar:"" },
       "None": { en: "None", de: "Kein",  jp: "無し", es: "", fr: "", ar:"" },
   //Square Gauge
       "OK": { en: "OK", de: "OK",  jp: "OK", es: "", fr: "", ar:"" },
       "Change gauge size": { en: "Change gauge size", de: "Ändere Anzeigen größe",  jp: "メーターサイズ変化", es: "", fr: "", ar:"" },
       "Text font size": { en: "Text font size", de: "Text Schriftart größe",  jp: "文字フォントサイズ", es: "", fr: "", ar:"" },
       "Text font style": { en: "Text font style", de: "Text Schriftart stil",  jp: "文字フォントスタイル", es: "", fr: "", ar:"" },
       "Gauge font size": { en: "Gauge font size", de: "Anzeigen Schriftart größe ",  jp: "メーターフォントサイズ", es: "", fr: "", ar:"" },
       "Gauge font style": { en: "Gauge font style", de: "Anzeigen Schriftart stil",  jp: "メーターフォントスタイル", es: "", fr: "", ar:"" },
       "Change main value": { en: "Change main value", de: "Ändere haupt wert",  jp: "主要値変更", es: "", fr: "", ar:"" },
       "Change sec value": { en: "Change sec value", de: "Ändere sekundär wert",  jp: "補助値変更", es: "", fr: "", ar:"" },
       "Change title": { en: "Change title", de: "Titel Ändern",  jp: "タイトル変更", es: "", fr: "", ar:"" },
       "Set decimal": { en: "decimal points", de: "Dezimal Punkte",  jp: "小数点設定", es: "", fr: "", ar:"" },
       "Set bar gauge max": { en: "Set bar gauge max", de: "Setze Balken Max.",  jp: "棒メーター最大", es: "", fr: "", ar:"" },
       "Toggle sec value": { en: "Toggle sec value", de: "Umschalten sekundär Wert",  jp: "補助値切り替え", es: "", fr: "", ar:"" },
        "Toggle vertical bar gauge": { en: "Toggle vertical bar gauge", de: "Umschalten vertikaler Balken",  jp: "垂直棒メーター切り替え", es: "", fr: "", ar:"" },
       "Toggle horizontal bar gauge": { en: "Toggle horizontal bar gauge", de: "Umschalten horizontaler Balken",  jp: "水平棒メーター切り替え", es: "", fr: "", ar:"" },
       "Set min warning": { en: "Set min warnin", de: "Setze min Warnung",  jp: "最小限の警告設定", es: "", fr: "", ar:"" },
       "Set max warning": { en: "Set max warning", de: "Setze max Warnung",  jp: "最大警告設定", es: "", fr: "", ar:"" },
       "Change unit symbol": { en: "Change unit symbol", de: "Ändere Symboleinheit",  jp: "単位記号変更", es: "", fr: "", ar:"" },
       "remove gauge": { en: "remove gauge", de: "Anzeige löschen",  jp: "メーターを抜かす", es: "", fr: "", ar:"" },
       "medium": { en: "medium", de: "mittel",  jp: "中", es: "", fr: "", ar:"" },
       "small": { en: "small", de: "klein",  jp: "小", es: "", fr: "", ar:"" },
       "large": { en: "large", de: "groß",  jp: "大", es: "", fr: "", ar:"" },
       "custom": { en: "custom", de: "benutzerdefiniert",  jp: "カスタム", es: "", fr: "", ar:"" },
   //Round Gauge
       "Start Stop values": { en: "Start Stop value", de: "Start Stop Werte",  jp: "開始値と終了値", es: "", fr: "", ar:"" },
       "Test sweep": { en: "Test sweep", de: "Nadel Test",  jp: "テストスイープ", es: "", fr: "", ar:"" },
       "Datasource": { en: "Datasource", de: "Datenquelle",  jp: "データソース", es: "", fr: "", ar:"" },
       "Size and ring": { en: "Size and ring", de: "Größe und Ring",  jp: "サイズとリング", es: "", fr: "", ar:"" },
       "Needle": { en: "Needle", de: "Nadel",  jp: "針", es: "", fr: "", ar:"" },
       "Needle trail": { en: "Needle trail", de: "Nadel Schweif",  jp: "針跡", es: "", fr: "", ar:"" },
       "Labels": { en: "Labels", de: "Beschriftungen",  jp: "ラベル", es: "", fr: "", ar:"" },
       "Major ticks": { en: "Major ticks", de: "Haupt Ticks",  jp: "主尺", es: "", fr: "", ar:"" },
       "Minor ticks": { en: "Minor ticks", de: "Untergeordnete Ticks",  jp: "副尺", es: "", fr: "", ar:"" },
       "Warnings": { en: "Warnings", de: "Warnungen",  jp: "警告", es: "", fr: "", ar:"" },
       "Description text": { en: "Description text", de: "Beschreibungs Text",  jp: "説明文字", es: "", fr: "", ar:"" },
       "Close menu": { en: "Close menu", de: "Menü schliessen",  jp: "メニューを閉じる", es: "", fr: "", ar:"" },
       "Gauge size": { en: "Gauge size", de: "Anzeigen Größe",  jp: "メーターサイズ", es: "", fr: "", ar:"" },
       "Backround color": { en: "Backround color", de: "Hintergrund Farbe",  jp: "背景色", es: "", fr: "", ar:"" },
       "Outer ring visible": { en: "Outer ring visible", de: "Ring Sichtbarkeit",  jp: "外輪可視", es: "", fr: "", ar:"" },
       "Needle button visible": { en: "Needle button visible", de: "Knopf Sichtbarkeit",  jp: "針のボタン可視", es: "", fr: "", ar:"" },
       "Needle visible": { en: "Needle visible", de: "Nadel Sichtbarkeit",  jp: "針可視", es: "", fr: "", ar:"" },
       "Delete gauge": { en: "Delete gauge", de: "Anzeige löschen",  jp: "メーター消す", es: "", fr: "", ar:"" },
       "Start value": { en: "Start value", de: "Start Wert",  jp: "開始値", es: "", fr: "", ar:"" },
       "End value": { en: "End value", de: "End Wert",  jp: "終了値", es: "", fr: "", ar:"" },
       "Start angle": { en: "Start angle", de: "Start Winkel",  jp: "開始角度", es: "", fr: "", ar:"" },
       "End angle": { en: "End angle", de: "End Winkel",  jp: "終了角度", es: "", fr: "", ar:"" },
       "Needle color": { en: "Needle color", de: "Nadel Farbe",  jp: "針色", es: "", fr: "", ar:"" },
       "Needle length": { en: "Needle lenght", de: "Nadel Länge",  jp: "針の長さ", es: "", fr: "", ar:"" },
       "Needle base width": { en: "Needle base width", de: "Nadel basis breite",  jp: "針の基部幅", es: "", fr: "", ar:"" },
       "Needle tip width": { en: "Needle tip width", de: "Nadel Spitzen breite",  jp: "針の先端幅", es: "", fr: "", ar:"" },
       "Needle offset": { en: "Needle offset", de: "Nadel offset",  jp: "針補正", es: "", fr: "", ar:"" },
       "Outer needle trail": { en: "Outer needle trail", de: "Oberer Nadel Schweif",  jp: "外針跡", es: "", fr: "", ar:"" },
       "Middle needle trail": { en: "Middle needle trail", de: "Mittlerer Nadel Schweif",  jp: "中針跡", es: "", fr: "", ar:"" },
       "Lower needle trail": { en: "Lower needle trail", de: "Unterer Nadel Schweif",  jp: "内針跡", es: "", fr: "", ar:"" },
       "Minor tickmark height": { en: "Minor tickmark heigh", de: "Tick Höhe",  jp: "副尺高さ", es: "", fr: "", ar:"" },
       "Minor tickmark width": { en: "Minor tickmark width", de: "Tick Breite",  jp: "副尺幅", es: "", fr: "", ar:"" },
       "Minor tickmark steps": { en: "Minor tickmark steps", de: "Tick Schritte",  jp: "副尺", es: "", fr: "", ar:"" },
       "Minor tickmark inset": { en: "Minor tickmark inset", de: "Tick Einsatz",  jp: "副尺差し込み", es: "", fr: "", ar:"" },
       "Minor tick active color": { en: "Minor tick active color", de: "Tick aktiv Farbe",  jp: "副尺停止中の色", es: "", fr: "", ar:"" },
       "Minor tick inactive color": { en: "Minor tick inactive color", de: "Untergeordnete Tick inaktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
       "Major tick steps": { en: "Major tick steps", de: "Haupt Ticks schritte",  jp: "主尺ステップ", es: "", fr: "", ar:"" },
       "Major tickmark height": { en: "Major tickmark height", de: "Haupt Ticks Höhe",  jp: "主尺高さ", es: "", fr: "", ar:"" },
       "Major tickmark width": { en: "Major tickmark width", de: "Haupt Ticks Breite",  jp: "主尺幅", es: "", fr: "", ar:"" },
       "Major tickmark inset": { en: "Major tickmark width", de: "Haupt Ticks Einsatz",  jp: "主尺差し込み", es: "", fr: "", ar:"" },
       "Tickmark active color": { en: "Tickmark active color", de: "Ticks aktiv Farbe",  jp: "主尺停止中の色", es: "", fr: "", ar:"" },
       "Tickmark inactive color": { en: "Tickmark inactive color", de: "Ticks inaktiv Farbe",  jp: "主尺停止中の色", es: "", fr: "", ar:"" },
       "Major label steps": { en: "Major label steps", de: "Haupt Label Schritte",  jp: "主ラベルステップ", es: "", fr: "", ar:"" },
       "Label size": { en: "Label size", de: "Label Größe",  jp: "ラベルサイズ", es: "", fr: "", ar:"" },
       "Label inset": { en: "Label inset", de: "Label Einsatz",  jp: "ラベル差し込み", es: "", fr: "", ar:"" },
       "Label Font": { en: "Label Font", de: "Label Schriftart",  jp: "ラベルフォント", es: "", fr: "", ar:"" },
       "Label active color": { en: "Label active color", de: "Label aktiv Farbe",  jp: "ラベル稼働中の色", es: "", fr: "", ar:"" },
       "Label inactive color": { en: "Label inactive color", de: "Label inaktiv Farbe",  jp: "ラベル停止中の色", es: "", fr: "", ar:"" },
       "Low warning trigger": { en: "Low warning trigger", de: "Unterer Warnungs Trigger",  jp: "最低値警告トリガー", es: "", fr: "", ar:"" },
       "High warning trigger": { en: "High warning trigger", de: "Oberer Warnungs Trigger",  jp: "最高値警告トリガー", es: "", fr: "", ar:"" },
       "Red area inset": { en: "Red area inset", de: "Rot Bereich Einsatz",  jp: "赤エリア差し込み", es: "", fr: "", ar:"" },
       "Red start": { en: "Red start", de: "Rot Start",  jp: "赤エリアスタート", es: "", fr: "", ar:"" },
       "Red area width": { en: "Red area width", de: "Rot Bereich Breite",  jp: "赤エリア幅", es: "", fr: "", ar:"" },
       "Horizontal position": { en: "Horizontal position", de: "Horizontale Position",  jp: "水平位", es: "", fr: "", ar:"" },
       "Vertical position": { en: "Vertical position", de: "Vertikale Position",  jp: "垂直位置", es: "", fr: "", ar:"" },
       "Fontsize": { en: "Fontsize", de: "Schriftgröße",  jp: "フォントサイズ", es: "", fr: "", ar:"" },
       "Font": { en: "Font", de: "Schriftart",  jp: "フォント", es: "", fr: "", ar:"" },
       "Font color": { en: "Font color", de: "Schrift Farbe",  jp: "フォント色", es: "", fr: "", ar:"" },
       "Display Text": { en: "Display Text", de: "Anzeige Text",  jp: "文字表示", es: "", fr: "", ar:"" },
   //State GIF
       "Source": { en: "Source", de: "Datenquelle",  jp: "ソース", es: "", fr: "", ar:"" },
       "Trigger": { en: "Trigger", de: "Trigger",  jp: "トリガー", es: "", fr: "", ar:"" },
       "Delete image": { en: "Delete image", de: "Bild löschen",  jp: "画像消去", es: "", fr: "", ar:"" },
   //Text Label
       "Warn value high": { en: "Warn value high", de: "Oberer Warnungs Wert",  jp: "最大警告値", es: "", fr: "", ar:"" },
       "Warn value low": { en: "Warn value low", de: "Unterer Warnungs Wert",  jp: "最低警告値", es: "", fr: "", ar:"" },
       "Delete": { en: "Delete", de: "Löschen",  jp: "消去", es: "", fr: "", ar:"" },
       "Use Datasource": { en: "Use Datasource", de: "Benutze Datenquelle",  jp: "データソース使用", es: "", fr: "", ar:"" },
   //State Picture
       "Image on": { en: "Image on value", de: "Bild an",  jp: "画像オン", es: "", fr: "", ar:"" },
       "Image off": { en: "Image off value", de: "Bild aus",  jp: "画像オフ", es: "", fr: "", ar:"" },
   //Bar Gauge
       "min value": { en: "min value", de: "Minimal Wert",  jp: "最低値", es: "", fr: "", ar:"" },
       "max value": { en: "max value", de: "Maximal Wert",  jp: "最大値", es: "", fr: "", ar:"" },
   //Color Bar
       "Frame color": { en: "Frame color", de: "Rahmen Farbe",  jp: "フレーム色", es: "", fr: "", ar:"" },
       "Backround color": { en: "Backround color", de: "Hintergrund Farbe",  jp: "背景色", es: "", fr: "", ar:"" },
       "Titlebar color": { en: "Titlebar color", de: "Titel Bar Farbe",  jp: "タイトル色", es: "", fr: "", ar:"" },
       "Bargauge color": { en: "Bargauge colore", de: "Bar Anzeige Farbe",  jp: "-帽メーター色", es: "", fr: "", ar:"" },
       "Title text color": { en: "Title text color", de: "Titel Text Farbe",  jp: "タイトル文字色", es: "", fr: "", ar:"" },
       "Main text color": { en: "Main text color", de: "Haupt Text Farbe",  jp: "メイン文字色", es: "", fr: "", ar:"" },


   // DATASOURCES Translation, Low priority as i have to find a way to get them to work in a Listmodel ...
       "DRIVESHAFT OFFSET":{ en: "DRIVESHAFT OFFSET", de: "German", jp: "ドライブシャフト補正", es: "", fr: "", ar:"" },
       "Average Fuel Economy":{ en: "", de: "", jp: "平均燃費", es: "", fr: "", ar:"" },
       "Alternator Light":{ en: "", de: "", jp: "オルタネーター光", es: "", fr: "", ar:"" },
       "Aux Temp 1":{ en: "", de: "", jp: "副温度 1", es: "", fr: "", ar:"" },
       "Overtemp Light":{ en: "", de: "", jp: "オーバーヒート光", es: "", fr: "", ar:"" },
       "OilP Light":{ en: "", de: "", jp: "油圧光", es: "", fr: "", ar:"" },
       "Auto Trans":{ en: "", de: "", jp: "オートマ　ミッション", es: "", fr: "", ar:"" },
       "activeboosttable":{ en: "", de: "", jp: "実行中のブーストテーブル", es: "", fr: "", ar:"" },
       "activetunetable":{ en: "", de: "", jp: "実行中のチューン", es: "", fr: "", ar:"" },
       "Analog0":{ en: "", de: "", jp: "アナログ0", es: "", fr: "", ar:"" },
       "Analog1":{ en: "", de: "", jp: "アナログ1", es: "", fr: "", ar:"" },
       "Analog2":{ en: "", de: "", jp: "アナログ2", es: "", fr: "", ar:"" },
       "Analog3":{ en: "", de: "", jp: "アナログ3", es: "", fr: "", ar:"" },
       "Analog4":{ en: "", de: "", jp: "アナログ4", es: "", fr: "", ar:"" },
       "Analog5":{ en: "", de: "", jp: "アナログ5", es: "", fr: "", ar:"" },
       "Analog6":{ en: "", de: "", jp: "アナログ6", es: "", fr: "", ar:"" },
       "Analog7":{ en: "", de: "", jp: "アナログ7", es: "", fr: "", ar:"" },
       "Analog8":{ en: "", de: "", jp: "アナログ8", es: "", fr: "", ar:"" },
       "Analog9":{ en: "", de: "", jp: "アナログ9", es: "", fr: "", ar:"" },
       "Analog10":{ en: "", de: "", jp: "アナログ10", es: "", fr: "", ar:"" },
       "Analog 0 Calc":{ en: "", de: "", jp: "アナログ0計算", es: "", fr: "", ar:"" },
       "Analog 1 Calc":{ en: "", de: "", jp: "アナログ1計算", es: "", fr: "", ar:"" },
       "Analog 2 Calc":{ en: "", de: "", jp: "アナログ2計算", es: "", fr: "", ar:"" },
       "Analog 3 Calc":{ en: "", de: "", jp: "アナログ3計算", es: "", fr: "", ar:"" },
       "Analog 4 Calc":{ en: "", de: "", jp: "アナログ4計算", es: "", fr: "", ar:"" },
       "Analog 5 Calc":{ en: "", de: "", jp: "アナログ5計算", es: "", fr: "", ar:"" },
       "Analog 6 Calc":{ en: "", de: "", jp: "アナログ6計算", es: "", fr: "", ar:"" },
       "Analog 7 Calc":{ en: "", de: "", jp: "アナログ7計算", es: "", fr: "", ar:"" },
       "Analog 8 Calc":{ en: "", de: "", jp: "アナログ8計算", es: "", fr: "", ar:"" },
       "Analog 9 Calc":{ en: "", de: "", jp: "アナログ9計算", es: "", fr: "", ar:"" },
       "Analog 10 Calc":{ en: "", de: "", jp: "アナログ10計算", es: "", fr: "", ar:"" },
       "Accel Ped Pos.":{ en: "", de: "", jp: "アクセルペダルの位置", es: "", fr: "", ar:"" },
       "Accel. Timmer":{ en: "", de: "", jp: "アクセルタイマー", es: "", fr: "", ar:"" },
       "X accel.":{ en: "", de: "", jp: "Xアクセル", es: "", fr: "", ar:"" },
       "Y accel.":{ en: "", de: "", jp: "Yアクセル", es: "", fr: "", ar:"" },
       "Z accel.":{ en: "", de: "", jp: "Zアクセル", es: "", fr: "", ar:"" },
       "AFR":{ en: "", de: "", jp: "空燃比", es: "", fr: "", ar:"" },
       "AFR L.BANK ACTUAL":{ en: "", de: "", jp: "左バンク空燃比(実際)", es: "", fr: "", ar:"" },
       "AFR R.BANK ACTUAL":{ en: "", de: "", jp: "右バンク空燃比(実際)", es: "", fr: "", ar:"" },
       "AFR L. BANK TARGET":{ en: "", de: "", jp: "左バンク空燃比(目標)", es: "", fr: "", ar:"" },
       "AFR R. BANK TARGET":{ en: "", de: "", jp: "右バンク空燃比(目標)", es: "", fr: "", ar:"" },
       "AFR CYL 1":{ en: "", de: "", jp: "シリンダー1空燃比", es: "", fr: "", ar:"" },
       "AFR CYL 2":{ en: "", de: "", jp: "シリンダー2空燃比", es: "", fr: "", ar:"" },
       "AFR CYL 3":{ en: "", de: "", jp: "シリンダー3空燃比", es: "", fr: "", ar:"" },
       "AFR CYL 4":{ en: "", de: "", jp: "シリンダー4空燃比", es: "", fr: "", ar:"" },
       "AFR CYL 5":{ en: "", de: "", jp: "シリンダー5空燃比", es: "", fr: "", ar:"" },
        "AFR CYL 6":{ en: "", de: "", jp: "シリンダー6空燃比", es: "", fr: "", ar:"" },
        "AFR CYL 7":{ en: "", de: "", jp: "シリンダー7空燃比", es: "", fr: "", ar:"" },
        "AFR CYL 8":{ en: "", de: "", jp: "シリンダー8空燃比", es: "", fr: "", ar:"" },
        "Air T.2":{ en: "", de: "", jp: "空気温度2", es: "", fr: "", ar:"" },
        "Ambi Pres.":{ en: "", de: "", jp: "周囲圧力", es: "", fr: "", ar:"" },
        "Ambi Temp.":{ en: "", de: "", jp: "周囲温度", es: "", fr: "", ar:"" },
        "Antilag sw.":{ en: "", de: "", jp: "アンチラグスイッチ", es: "", fr: "", ar:"" },
        "Antilag launch":{ en: "", de: "", jp: "アンチラグローンチ", es: "", fr: "", ar:"" },
        "AUX Calc1":{ en: "", de: "", jp: "副計算値1", es: "", fr: "", ar:"" },
        "AUX Calc2":{ en: "", de: "", jp: "副計算値2", es: "", fr: "", ar:"" },
        "AUX Calc3":{ en: "", de: "", jp: "副計算値3", es: "", fr: "", ar:"" },
        "AUX Calc4":{ en: "", de: "", jp: "副計算値4", es: "", fr: "", ar:"" },
        "AUX Rev Limit Sw":{ en: "", de: "", jp: "副レブリミットスイッチ", es: "", fr: "", ar:"" },
        "AUX Temp":{ en: "", de: "", jp: "副温度", es: "", fr: "", ar:"" },
        "Av. Fuel Economy":{ en: "", de: "", jp: "平均燃費", es: "", fr: "", ar:"" },
        "Battery Light":{ en: "", de: "", jp: "バッテリー光", es: "", fr: "", ar:"" },
        "Boost Ctrl.":{ en: "", de: "", jp: "ブーストコントロール", es: "", fr: "", ar:"" },
        "BOOST OFFSET":{ en: "", de: "", jp: "ブースト補正", es: "", fr: "", ar:"" },
        "Boost Duty":{ en: "", de: "", jp: "ブーストデューティ", es: "", fr: "", ar:"" },
        "Linear boost":{ en: "", de: "", jp: "リニアブースト", es: "", fr: "", ar:"" },
        "Boost Tp":{ en: "", de: "", jp: "ブーストTP", es: "", fr: "", ar:"" },
        "Boost Wg":{ en: "", de: "", jp: "WGブースト", es: "", fr: "", ar:"" },
        "Brake Pedal":{ en: "", de: "", jp: "ブレーキペダル", es: "", fr: "", ar:"" },
        "Brake Pressure":{ en: "", de: "", jp: "ブレーキ圧力", es: "", fr: "", ar:"" },
        "Clutch Sw":{ en: "", de: "", jp: "クラッチスイッチ", es: "", fr: "", ar:"" },
        "Calibration select":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
        "Coolant P.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
        "Cyl1 O2 Corr.":{ en: "", de: "", jp: "シリンダー1 o2修正", es: "", fr: "", ar:"" },
        "Cyl2 O2 Corr.":{ en: "", de: "", jp: "シリンダー2 o2修正", es: "", fr: "", ar:"" },
        "Cyl3 O2 Corr.":{ en: "", de: "", jp: "シリンダー3 o2修正", es: "", fr: "", ar:"" },
        "Cyl4 O2 Corr.":{ en: "", de: "", jp: "シリンダー4 o2修正", es: "", fr: "", ar:"" },
        "Cyl5 O2 Corr.":{ en: "", de: "", jp: "シリンダー5 o2修正", es: "", fr: "", ar:"" },
        "Cyl6 O2 Corr.":{ en: "", de: "", jp: "シリンダー6 o2修正", es: "", fr: "", ar:"" },
        "Cyl7 O2 Corr.":{ en: "", de: "", jp: "シリンダー7 o2修正", es: "", fr: "", ar:"" },
        "Cyl8 O2 Corr.":{ en: "", de: "", jp: "シリンダー8 o2修正", es: "", fr: "", ar:"" },
        "Decel Cut":{ en: "", de: "", jp: "減速燃料カット", es: "", fr: "", ar:"" },
        "Diff Oil T.":{ en: "", de: "", jp: "デフ油温度", es: "", fr: "", ar:"" },
        "DigitalInput 1":{ en: "", de: "", jp: "デジタル入力1", es: "", fr: "", ar:"" },
        "DigitalInput 2":{ en: "", de: "", jp: "デジタル入力2", es: "", fr: "", ar:"" },
        "DigitalInput 3":{ en: "", de: "", jp: "デジタル入力3", es: "", fr: "", ar:"" },
        "DigitalInput 4":{ en: "", de: "", jp: "デジタル入力4", es: "", fr: "", ar:"" },
        "DigitalInput 5":{ en: "", de: "", jp: "デジタル入力5", es: "", fr: "", ar:"" },
        "DigitalInput 6":{ en: "", de: "", jp: "デジタル入力6", es: "", fr: "", ar:"" },
        "DigitalInput 7":{ en: "", de: "", jp: "デジタル入力7", es: "", fr: "", ar:"" },
       "Dist. To Empty":{ en: "", de: "", jp: "残り走行距離", es: "", fr: "", ar:"" },
       "Dwell":{ en: "", de: "", jp: "長引く", es: "", fr: "", ar:"" },
       "ECU CPU temp":{ en: "", de: "", jp: "ECU温度", es: "", fr: "", ar:"" },
       "EGT 1":{ en: "", de: "", jp: "排気ガス温度1", es: "", fr: "", ar:"" },
       "EGT 2":{ en: "", de: "", jp: "排気ガス温度2", es: "", fr: "", ar:"" },
       "EGT 3":{ en: "", de: "", jp: "排気ガス温度3", es: "", fr: "", ar:"" },
       "EGT 4":{ en: "", de: "", jp: "排気ガス温度4", es: "", fr: "", ar:"" },
       "EGT 5":{ en: "", de: "", jp: "排気ガス温度5", es: "", fr: "", ar:"" },
       "EGT 6":{ en: "", de: "", jp: "排気ガス温度6", es: "", fr: "", ar:"" },
       "EGT 7":{ en: "", de: "", jp: "排気ガス温度7", es: "", fr: "", ar:"" },
       "EGT 8":{ en: "", de: "", jp: "排気ガス温度8", es: "", fr: "", ar:"" },
       "EGT 9":{ en: "", de: "", jp: "排気ガス温度9", es: "", fr: "", ar:"" },
       "EGT 10":{ en: "", de: "", jp: "排気ガス温度10", es: "", fr: "", ar:"" },
       "EGT 11":{ en: "", de: "", jp: "排気ガス温度11", es: "", fr: "", ar:"" },
       "EGT 12":{ en: "", de: "", jp: "排気ガス温度12", es: "", fr: "", ar:"" },
       "EGT highest":{ en: "", de: "", jp: "最高排気ガス温度", es: "", fr: "", ar:"" },
       "EGT diff.":{ en: "", de: "", jp: "排気ガス温度補正", es: "", fr: "", ar:"" },
       "Eng. Load":{ en: "", de: "", jp: "エンジンロード", es: "", fr: "", ar:"" },
       "Exhaust Cam 1":{ en: "", de: "", jp: "-エギゾーストカム1", es: "", fr: "", ar:"" },
       "Exhaust Cam 2":{ en: "", de: "", jp: "-エギゾーストカム2", es: "", fr: "", ar:"" },
       "Flag1":{ en: "", de: "", jp: "ステータス1", es: "", fr: "", ar:"" },
       "Flag2":{ en: "", de: "", jp: "ステータス2", es: "", fr: "", ar:"" },
       "Flag3":{ en: "", de: "", jp: "ステータス3", es: "", fr: "", ar:"" },
       "Flag4":{ en: "", de: "", jp: "ステータス4", es: "", fr: "", ar:"" },
       "Flag5":{ en: "", de: "", jp: "ステータス5", es: "", fr: "", ar:"" },
       "Flag6":{ en: "", de: "", jp: "ステータス6", es: "", fr: "", ar:"" },
       "Flag7":{ en: "", de: "", jp: "ステータス7", es: "", fr: "", ar:"" },
       "Flag8":{ en: "", de: "", jp: "ステータス8", es: "", fr: "", ar:"" },
       "Flag9":{ en: "", de: "", jp: "ステータス9", es: "", fr: "", ar:"" },
       "Flag10":{ en: "", de: "", jp: "ステータス10", es: "", fr: "", ar:"" },
       "Flag11":{ en: "", de: "", jp: "ステータス11", es: "", fr: "", ar:"" },
       "Flag12":{ en: "", de: "", jp: "ステータス12", es: "", fr: "", ar:"" },
       "Flag13":{ en: "", de: "", jp: "ステータス13", es: "", fr: "", ar:"" },
       "Flag14":{ en: "", de: "", jp: "ステータス14", es: "", fr: "", ar:"" },
       "Flag15":{ en: "", de: "", jp: "ステータス15", es: "", fr: "", ar:"" },
       "Flag16":{ en: "", de: "", jp: "ステータス16", es: "", fr: "", ar:"" },
       "Flag17":{ en: "", de: "", jp: "ステータス17", es: "", fr: "", ar:"" },
       "Flag18":{ en: "", de: "", jp: "ステータス18", es: "", fr: "", ar:"" },
       "Flag19":{ en: "", de: "", jp: "ステータス19", es: "", fr: "", ar:"" },
       "Flag20":{ en: "", de: "", jp: "ステータス20", es: "", fr: "", ar:"" },
       "Flag21":{ en: "", de: "", jp: "ステータス21", es: "", fr: "", ar:"" },
       "Flag22":{ en: "", de: "", jp: "ステータス22", es: "", fr: "", ar:"" },
       "Flag23":{ en: "", de: "", jp: "ステータス23", es: "", fr: "", ar:"" },
       "Flag24":{ en: "", de: "", jp: "ステータス24", es: "", fr: "", ar:"" },
       "Flag25":{ en: "", de: "", jp: "ステータス25", es: "", fr: "", ar:"" },
       "IGN Angle B1":{ en: "", de: "", jp: "IGN角度バンク1", es: "", fr: "", ar:"" },
       "IGN Angle B2":{ en: "", de: "", jp: "IGN角度バンク2", es: "", fr: "", ar:"" },
       "FSL COMMAND":{ en: "", de: "", jp: "FSL COMMAND", es: "", fr: "", ar:"" },
       "FSL INDEX":{ en: "", de: "", jp: "FSL INDEX", es: "", fr: "", ar:"" },
       "Flat Shift":{ en: "", de: "", jp: "フラットシフト", es: "", fr: "", ar:"" },
       "Fuel Correction":{ en: "", de: "", jp: "燃料補正", es: "", fr: "", ar:"" },
       "Fuel cor. level":{ en: "", de: "", jp: "燃料補正レベル", es: "", fr: "", ar:"" },
       "Fuel tank level":{ en: "", de: "", jp: "燃料レベル", es: "", fr: "", ar:"" },
       "Ethanol":{ en: "", de: "", jp: "エタノール", es: "", fr: "", ar:"" },
       "Fuel Cons.":{ en: "", de: "", jp: "燃費", es: "", fr: "", ar:"" },
       "Fuel Cut":{ en: "", de: "", jp: "燃料カット", es: "", fr: "", ar:"" },
       "Fuel flow":{ en: "", de: "", jp: "燃料流量", es: "", fr: "", ar:"" },
       "Fuel flow dif.":{ en: "", de: "", jp: "燃料流量差", es: "", fr: "", ar:"" },
       "Fuel flow ret.":{ en: "", de: "", jp: "燃料流量リターン", es: "", fr: "", ar:"" },
       "Fuel Pres.":{ en: "", de: "", jp: "燃料圧力", es: "", fr: "", ar:"" },
       "Fuel T.":{ en: "", de: "", jp: "燃料トリム", es: "", fr: "", ar:"" },
       "Fuel trim long B1":{ en: "", de: "", jp: "燃料トリムLong B1", es: "", fr: "", ar:"" },
       "Fuel trim long B2":{ en: "", de: "", jp: "燃料トリム Long B2", es: "", fr: "", ar:"" },
       "Fuel trim short B1":{ en: "", de: "", jp: "燃料トリム Short B1", es: "", fr: "", ar:"" },
       "Fuel trim short B2":{ en: "", de: "", jp: "燃料トリム Short B2", es: "", fr: "", ar:"" },
       "Gear offset":{ en: "", de: "", jp: "ギヤ偏差", es: "", fr: "", ar:"" },
       "Gear sw.":{ en: "", de: "", jp: "ギヤスイッチ", es: "", fr: "", ar:"" },
       "Gear Oil Pres.":{ en: "", de: "", jp: "ギヤオイル圧力", es: "", fr: "", ar:"" },
       "Generic out 1":{ en: "", de: "", jp: "汎用アウトプット1", es: "", fr: "", ar:"" },
       "GPS Altitude":{ en: "", de: "", jp: "GPS高度", es: "", fr: "", ar:"" },
       "GPS Latitude":{ en: "", de: "", jp: "GPS緯度", es: "", fr: "", ar:"" },
       "GPS Longitude":{ en: "", de: "", jp: "GPS経度", es: "", fr: "", ar:"" },
       "GPS Speed":{ en: "", de: "", jp: "GPS速度", es: "", fr: "", ar:"" },
       "GPS Time":{ en: "", de: "", jp: "GPS時間", es: "", fr: "", ar:"" },
       "GPS Visible Satelites":{ en: "", de: "", jp: "GPS実行中衛星", es: "", fr: "", ar:"" },
       "Gyro X":{ en: "", de: "", jp: "ジャイロX", es: "", fr: "", ar:"" },
       "Giro Y":{ en: "", de: "", jp: "ジャイロY", es: "", fr: "", ar:"" },
       "Gyro Z":{ en: "", de: "", jp: "ジャイロZ", es: "", fr: "", ar:"" },
       "Handbrake":{ en: "", de: "", jp: "サイドブレーキ", es: "", fr: "", ar:"" },
       "Highbeam":{ en: "", de: "", jp: "ハイビーム", es: "", fr: "", ar:"" },
       "Lowbeam":{ en: "", de: "", jp: "ロービーム", es: "", fr: "", ar:"" },
       "Homecounter":{ en: "", de: "", jp: "ホームカウンター", es: "", fr: "", ar:"" },
       "Idle Val.":{ en: "", de: "", jp: "アイドルバリュー", es: "", fr: "", ar:"" },
       "Ignition":{ en: "", de: "", jp: "IGN ", es: "", fr: "", ar:"" },
       "Ignition 1":{ en: "", de: "", jp: "IGN 1", es: "", fr: "", ar:"" },
       "Ignition 2":{ en: "", de: "", jp: "IGN 2", es: "", fr: "", ar:"" },
       "Ignition 3":{ en: "", de: "", jp: "IGN 3", es: "", fr: "", ar:"" },
       "Ignition 4":{ en: "", de: "", jp: "IGN 4", es: "", fr: "", ar:"" },
       "Inlet Cam 1 angle":{ en: "", de: "", jp: "インレットカム1角度", es: "", fr: "", ar:"" },
       "Inlet Cam 2 angle":{ en: "", de: "", jp: "インレットカム2角度", es: "", fr: "", ar:"" },
       "Inj. Duty 1":{ en: "", de: "", jp: "-INJ Duty 1", es: "", fr: "", ar:"" },
       "Inj. Angle":{ en: "", de: "", jp: "INJ角度", es: "", fr: "", ar:"" },
       "Inj. Duty 2":{ en: "", de: "", jp: "INJ Duty 2", es: "", fr: "", ar:"" },
       "Inj. Duty 3":{ en: "", de: "", jp: "INJ Duty 3", es: "", fr: "", ar:"" },
       "Inj. Duty 4":{ en: "", de: "", jp: "INJ Duty 4", es: "", fr: "", ar:"" },
       "Inj. Duty":{ en: "", de: "", jp: "INJ Duty", es: "", fr: "", ar:"" },
       "Inj. Duty sec":{ en: "", de: "", jp: "INJ duty 副", es: "", fr: "", ar:"" },
       "Inj timing.":{ en: "", de: "", jp: "INJ タイミング", es: "", fr: "", ar:"" },
       "IAT":{ en: "", de: "", jp: "IAT", es: "", fr: "", ar:"" },
       "ISCV duty":{ en: "", de: "", jp: "ISCV Duty", es: "", fr: "", ar:"" },
       "Knocklevel 1":{ en: "", de: "", jp: "ノックレベル1", es: "", fr: "", ar:"" },
       "Knocklevel 2":{ en: "", de: "", jp: "ノックレベル2", es: "", fr: "", ar:"" },
       "Knock restard 1":{ en: "", de: "", jp: "ノックリタード1", es: "", fr: "", ar:"" },
       "Knock restard 2":{ en: "", de: "", jp: "ノックリタード2", es: "", fr: "", ar:"" },
       "Knock all peak":{ en: "", de: "", jp: "ノック全て頂上", es: "", fr: "", ar:"" },
       "Knock correction":{ en: "", de: "", jp: "ノック補正", es: "", fr: "", ar:"" },
       "Knock last cylinder":{ en: "", de: "", jp: "ノックラストシリンダー", es: "", fr: "", ar:"" },
       "Lambda 1":{ en: "", de: "", jp: "ラムダ1", es: "", fr: "", ar:"" },
       "Lambda 2":{ en: "", de: "", jp: "ラムダ2", es: "", fr: "", ar:"" },
       "Lambda 3":{ en: "", de: "", jp: "ラムダ3", es: "", fr: "", ar:"" },
       "Lambda 4":{ en: "", de: "", jp: "ラムダ4", es: "", fr: "", ar:"" },
       "Lambda Target":{ en: "", de: "", jp: "ラムダ目標", es: "", fr: "", ar:"" },
       "Current LAP No":{ en: "", de: "", jp: "Lap no. (現在)", es: "", fr: "", ar:"" },
       "Lap Time":{ en: "", de: "", jp: "Lap Time", es: "", fr: "", ar:"" },
       "Best Laptime":{ en: "", de: "", jp: "Best Lap Time", es: "", fr: "", ar:"" },
       "Launch control fuel enrich":{ en: "", de: "", jp: "LC 燃料エンリッチ", es: "", fr: "", ar:"" },
       "Launch control ign ret.":{ en: "", de: "", jp: "LC IGN リタード", es: "", fr: "", ar:"" },
       "Leading ign":{ en: "", de: "", jp: "リーディングIGN", es: "", fr: "", ar:"" },
       "left indicator":{ en: "", de: "", jp: "左ウィンカー", es: "", fr: "", ar:"" },
       "Limp mode":{ en: "", de: "", jp: "リンプモード", es: "", fr: "", ar:"" },
       "MAF 1 Volt":{ en: "", de: "", jp: "MAF 1 電圧", es: "", fr: "", ar:"" },
       "MAF 2 Volt":{ en: "", de: "", jp: "MAF 2 電圧", es: "", fr: "", ar:"" },
       "MAF activity":{ en: "", de: "", jp: "MAF 活動", es: "", fr: "", ar:"" },
       "MAP":{ en: "", de: "", jp: "MAP", es: "", fr: "", ar:"" },
       "MAP2":{ en: "", de: "", jp: "MAP 2", es: "", fr: "", ar:"" },
       "M.I.L":{ en: "", de: "", jp: "M.I.L", es: "", fr: "", ar:"" },
       "Miss count":{ en: "", de: "", jp: "ミス数", es: "", fr: "", ar:"" },
       "Master speed":{ en: "", de: "", jp: "マスター速度", es: "", fr: "", ar:"" },
       "Metering Oil Pump":{ en: "", de: "", jp: "測光オイルポンプ", es: "", fr: "", ar:"" },
       "Speed":{ en: "", de: "", jp: "速度", es: "", fr: "", ar:"" },
       "NOS":{ en: "", de: "", jp: "NOS", es: "", fr: "", ar:"" },
       "NOS Pres.":{ en: "", de: "", jp: "NOS圧力", es: "", fr: "", ar:"" },
       "NOS sw.":{ en: "", de: "", jp: "NOS スイッチ", es: "", fr: "", ar:"" },
       "O2 Volt 1":{ en: "", de: "", jp: "O2電圧 1", es: "", fr: "", ar:"" },
       "O2 Volt 2":{ en: "", de: "", jp: "O2電圧 2", es: "", fr: "", ar:"" },
       "O2 CORR R BANK ":{ en: "", de: "", jp: "O2 補正 R Bank", es: "", fr: "", ar:"" },
       "O2 CORR L BANK":{ en: "", de: "", jp: "O2 補正 L Bank", es: "", fr: "", ar:"" },
       "Odometer":{ en: "", de: "", jp: "走行距離", es: "", fr: "", ar:"" },
       "Oil Pres":{ en: "", de: "", jp: "油圧", es: "", fr: "", ar:"" },
       "Oil Temp.":{ en: "", de: "", jp: "油温度", es: "", fr: "", ar:"" },
       "PAN VAC":{ en: "", de: "", jp: "PAN VAC", es: "", fr: "", ar:"" },
       "PIM":{ en: "", de: "", jp: "PIM", es: "", fr: "", ar:"" },
       "Power":{ en: "", de: "", jp: "パワー", es: "", fr: "", ar:"" },
       "MAP Volt.":{ en: "", de: "", jp: "MAP電圧", es: "", fr: "", ar:"" },
       "Pri. Inj pulse width":{ en: "", de: "", jp: "主要インジェクター脈幅", es: "", fr: "", ar:"" },
       "Rally antilag sw.":{ en: "", de: "", jp: "ラリーアンチラグスイッチ", es: "", fr: "", ar:"" },
       "Right Indicator":{ en: "", de: "", jp: "右ウィンカー", es: "", fr: "", ar:"" },
       "REV LIM 3STEP":{ en: "", de: "", jp: "3ステップレブリミット", es: "", fr: "", ar:"" },
       "REV LIM 2STEP":{ en: "", de: "", jp: "2ステップレブリミット", es: "", fr: "", ar:"" },
       "REV LIM HIGHSIDE":{ en: "", de: "", jp: "最大レブリミット", es: "", fr: "", ar:"" },
       "REV LIM BOURNOUT":{ en: "", de: "", jp: "Burnout レブリミット", es: "", fr: "", ar:"" },
       "RPM":{ en: "", de: "", jp: "RPM", es: "", fr: "", ar:"" },
       "Rorary Trimpot 1":{ en: "", de: "", jp: "ロータリー Trimpot 1", es: "", fr: "", ar:"" },
       "Rorary Trimpot 2":{ en: "", de: "", jp: "ロータリー Trimpot 2", es: "", fr: "", ar:"" },
       "Rorary Trimpot 3":{ en: "", de: "", jp: "ロータリー Trimpot 3", es: "", fr: "", ar:"" },
       "Secondary Inj. Pulse width":{ en: "", de: "", jp: "2番インジェクター脈幅", es: "", fr: "", ar:"" },
       "Slave speed":{ en: "", de: "", jp: "レリーズスピード", es: "", fr: "", ar:"" },
       "Sensor 1":{ en: "", de: "", jp: "センサー1", es: "", fr: "", ar:"" },
       "Sensor 2":{ en: "", de: "", jp: "センサー2", es: "", fr: "", ar:"" },
       "Sensor 3":{ en: "", de: "", jp: "センサー3", es: "", fr: "", ar:"" },
       "Sensor 4":{ en: "", de: "", jp: "センサー4", es: "", fr: "", ar:"" },
       "Sensor 1":{ en: "", de: "", jp: "センサー5", es: "", fr: "", ar:"" },
       "Sensor 5":{ en: "", de: "", jp: "センサー6", es: "", fr: "", ar:"" },
       "Sensor 6":{ en: "", de: "", jp: "センサー7", es: "", fr: "", ar:"" },
       "Sensor 7":{ en: "", de: "", jp: "センサー8", es: "", fr: "", ar:"" },
       "Steering Wheel Angle":{ en: "", de: "", jp: "ステアリングホイール角度", es: "", fr: "", ar:"" },
       "Target Boost":{ en: "", de: "", jp: "目標ブースト", es: "", fr: "", ar:"" },
       "TPS V":{ en: "", de: "", jp: "TPS (電圧)", es: "", fr: "", ar:"" },
       "Timed duty 1":{ en: "", de: "", jp: "Timed Duty 1", es: "", fr: "", ar:"" },
       "Timed duty 2":{ en: "", de: "", jp: "Timed Duty 2", es: "", fr: "", ar:"" },
       "Timed duty output active":{ en: "", de: "", jp: "Timed Duty 機能稼働", es: "", fr: "", ar:"" },
       "Torque":{ en: "", de: "", jp: "トルク", es: "", fr: "", ar:"" },
       "Torque red. cut active":{ en: "", de: "", jp: "Torque red. cut active", es: "", fr: "", ar:"" },
       "Torque red. level active":{ en: "", de: "", jp: "Torque red. level active", es: "", fr: "", ar:"" },
       "TCS OFFSET":{ en: "", de: "", jp: "TCS補正", es: "", fr: "", ar:"" },
       "TC COMMAND":{ en: "", de: "", jp: "TC コマンド", es: "", fr: "", ar:"" },
       "Traction Control":{ en: "", de: "", jp: "トラクションコントロール", es: "", fr: "", ar:"" },
       "Trailing Ign.":{ en: "", de: "", jp: "トレイリング IGN", es: "", fr: "", ar:"" },
       "Transient throttle active":{ en: "", de: "", jp: "トレイリング IGN", es: "", fr: "", ar:"" },
       "Transmission Oil T.":{ en: "", de: "", jp: "ミッションオイル温度", es: "", fr: "", ar:"" },
       "Trigger Counter":{ en: "", de: "", jp: "トリガーカウンター", es: "", fr: "", ar:"" },
       "Triggers since last home":{ en: "", de: "", jp: "前回のホームからのトリガー", es: "", fr: "", ar:"" },
       "Trim":{ en: "", de: "", jp: "トリム", es: "", fr: "", ar:"" },
       "Trip meter":{ en: "", de: "", jp: "区間距離", es: "", fr: "", ar:"" },
       "Turbo rpm":{ en: "", de: "", jp: "ターボ回転数", es: "", fr: "", ar:"" },
       "Turbo rpm 2":{ en: "", de: "", jp: "ターボ回転数2", es: "", fr: "", ar:"" },
       "User Channel 1":{ en: "", de: "", jp: "ユーザーチャンネル1", es: "", fr: "", ar:"" },
       "User Channel 2":{ en: "", de: "", jp: "ユーザーチャンネル2", es: "", fr: "", ar:"" },
       "User Channel 3":{ en: "", de: "", jp: "ユーザーチャンネル3", es: "", fr: "", ar:"" },
       "User Channel 4":{ en: "", de: "", jp: "ユーザーチャンネル4", es: "", fr: "", ar:"" },
       "User Channel 5":{ en: "", de: "", jp: "ユーザーチャンネル5", es: "", fr: "", ar:"" },
       "User Channel 6":{ en: "", de: "", jp: "ユーザーチャンネル6", es: "", fr: "", ar:"" },
       "User Channel 7":{ en: "", de: "", jp: "ユーザーチャンネル7", es: "", fr: "", ar:"" },
       "User Channel 8":{ en: "", de: "", jp: "ユーザーチャンネル8", es: "", fr: "", ar:"" },
       "User Channel 9":{ en: "", de: "", jp: "ユーザーチャンネル9", es: "", fr: "", ar:"" },
       "User Channel 10":{ en: "", de: "", jp: "ユーザーチャンネル10", es: "", fr: "", ar:"" },
       "User Channel 11":{ en: "", de: "", jp: "ユーザーチャンネル11", es: "", fr: "", ar:"" },
       "User Channel 12":{ en: "", de: "", jp: "ユーザーチャンネル12", es: "", fr: "", ar:"" },
       "User Channel 13":{ en: "", de: "", jp: "ユーザーチャンネル13", es: "", fr: "", ar:"" },
       "Waste gate Pres.":{ en: "", de: "", jp: "ウェイストゲート圧力", es: "", fr: "", ar:"" },
       "ECT":{ en: "", de: "", jp: "ECT", es: "", fr: "", ar:"" },
       "Wheel speed difference":{ en: "", de: "", jp: "車輪速度補正", es: "", fr: "", ar:"" },
       "Wheel slip":{ en: "", de: "", jp: "", es: "ホイールスリップ", fr: "", ar:"" },
       "Wheel speed left front":{ en: "", de: "", jp: "ホイール加速(左前)", es: "", fr: "", ar:"" },
       "Wheel speed right front":{ en: "", de: "", jp: "ホイール加速 (左後)", es: "", fr: "", ar:"" },
       "Wheel speed left rear":{ en: "", de: "", jp: "ホイール加速(右前)", es: "", fr: "", ar:"" },
       "Wheel speed right rear":{ en: "", de: "", jp: "ホイール加速(右後)", es: "", fr: "", ar:"" },
       "Battery Voltage":{ en: "", de: "", jp: "バッテリー電圧", es: "", fr: "", ar:"" },
       "Boost (abs.)":{ en: "", de: "", jp: "ブースト", es: "", fr: "", ar:"" },
       "Error":{ en: "", de: "", jp: "エラー", es: "", fr: "", ar:"" },
       "IGBTPhaseATemp":{ en: "", de: "", jp: "IGBTPhaseA温度", es: "", fr: "", ar:"" },
       "IGBTPhaseBTemp":{ en: "", de: "", jp: "IGBTPhaseB温度", es: "", fr: "", ar:"" },
       "IGBTPhaseCTemp":{ en: "", de: "", jp: "IGBTPhaseC温度", es: "", fr: "", ar:"" },
       "GateDriverTemp":{ en: "", de: "", jp: "GateDriver温度", es: "", fr: "", ar:"" },
       "ControlBoardTemp":{ en: "", de: "", jp: "ControlBoard温度", es: "", fr: "", ar:"" },
       "DigInput1FowardSw":{ en: "", de: "", jp: "デジタル入力1 フォワードスイッチ", es: "", fr: "", ar:"" },
       "RtdTemp2":{ en: "", de: "", jp: "RTD温度2", es: "", fr: "", ar:"" },
       "RtdTemp3":{ en: "", de: "", jp: "RTD温度3", es: "", fr: "", ar:"" },
       "RtdTemp4":{ en: "", de: "", jp: "RTD温度4", es: "", fr: "", ar:"" },
       "RtdTemp5":{ en: "", de: "", jp: "RTD温度5", es: "", fr: "", ar:"" },
       "EMotorTemperature":{ en: "", de: "", jp: "モーター温度", es: "", fr: "", ar:"" },
       "TorqueShudder":{ en: "", de: "", jp: "トルク震え", es: "", fr: "", ar:"" },
       "DigInput2ReverseSwDigInput2ReverseSw":{ en: "", de: "", jp: "デジタル入力バックスイッチ", es: "", fr: "", ar:"" },
       "DigInput3BrakeSw":{ en: "", de: "", jp: "デジタル入力3ブレーキスィッチ", es: "", fr: "", ar:"" },
       "DigInput4RegenDisableSw":{ en: "", de: "", jp: "デジタル入力4REGEN解除", es: "", fr: "", ar:"" },
       "DigInput5IgnSw":{ en: "", de: "", jp: "デジタル入力5IGNスイッチ", es: "", fr: "", ar:"" },
       "DigInput6StartSw":{ en: "", de: "", jp: "デジタル入力6スタートスィッチ", es: "", fr: "", ar:"" },
       "DigInput7Bool":{ en: "", de: "", jp: "デジタル入力7Bool", es: "", fr: "", ar:"" },
       "DigInput8Bool":{ en: "", de: "", jp: "デジタル入力8Bool", es: "", fr: "", ar:"" },
       "EMotorAngle":{ en: "", de: "", jp: "-Eモーター角度", es: "", fr: "", ar:"" },
       "ElectricalOutFreq":{ en: "", de: "", jp: "電気出力周波数", es: "", fr: "", ar:"" },
       "DeltaResolverFiltered":{ en: "", de: "", jp: "Delta Resolver Filtered", es: "", fr: "", ar:"" },
       "PhaseACurrent":{ en: "", de: "", jp: "Phase A 電流", es: "", fr: "", ar:"" },
       "EMotorSpeed":{ en: "", de: "", jp: "Eモーター速度", es: "", fr: "", ar:"" },
       "PhaseBCurrent":{ en: "", de: "", jp: "Phase B 電流", es: "", fr: "", ar:"" },
       "PhaseCCurrent":{ en: "", de: "", jp: "Phase C 電流", es: "", fr: "", ar:"" },
       "DCBusCurrent":{ en: "", de: "", jp: "DC bus 電流", es: "", fr: "", ar:"" },
       "DCBusVoltage":{ en: "", de: "", jp: "Dc Bus 電圧", es: "", fr: "", ar:"" },
       "OutputVoltage":{ en: "", de: "", jp: "出力電圧", es: "", fr: "", ar:"" },
       "VABvdVoltage":{ en: "", de: "", jp: "VABVd電圧", es: "", fr: "", ar:"" },
       "VBCvqVoltage":{ en: "", de: "", jp: "VBCvq電圧", es: "", fr: "", ar:"" },
       "TiretempLF":{ en: "", de: "", jp: "タイヤ温度 (左前)", es: "", fr: "", ar:"" },
       "TiretempRF":{ en: "", de: "", jp: "タイヤ温度 (右前)", es: "", fr: "", ar:"" },
       "TiretempLR":{ en: "", de: "", jp: "タイヤ温度 (左後)", es: "", fr: "", ar:"" },
       "TiretempRR":{ en: "", de: "", jp: "タイヤ温度 (右後)", es: "", fr: "", ar:"" },
       "TirepresLF":{ en: "", de: "", jp: "タイヤ温度 (左前)", es: "", fr: "", ar:"" },
       "TirepresRF":{ en: "", de: "", jp: "タイヤ温度 (右前)", es: "", fr: "", ar:"" },
       "TirepresLR":{ en: "", de: "", jp: "タイヤ温度 (左後)", es: "", fr: "", ar:"" },
       "TirepresRR":{ en: "", de: "", jp: "タイヤ温度 (右後)", es: "", fr: "", ar:"" },
       "EX AnalogInput 0":{ en: "", de: "", jp: "I/Oアナログ入力0", es: "", fr: "", ar:"" },
       "EX AnalogInput 1":{ en: "", de: "", jp: "I/Oアナログ入力1", es: "", fr: "", ar:"" },
       "EX AnalogInput 2":{ en: "", de: "", jp: "I/Oアナログ入力2", es: "", fr: "", ar:"" },
       "EX AnalogInput 3":{ en: "", de: "", jp: "I/Oアナログ入力3", es: "", fr: "", ar:"" },
       "EX AnalogInput 4":{ en: "", de: "", jp: "I/Oアナログ入力4", es: "", fr: "", ar:"" },
       "EX AnalogInput 5":{ en: "", de: "", jp: "I/Oアナログ入力5", es: "", fr: "", ar:"" },
       "EX AnalogInput 6":{ en: "", de: "", jp: "I/Oアナログ入力6", es: "", fr: "", ar:"" },
       "EX AnalogInput 7":{ en: "", de: "", jp: "I/Oアナログ入力7", es: "", fr: "", ar:"" },
       "EX Analog Calc 0":{ en: "", de: "", jp: "-I/O アナログ計算0", es: "", fr: "", ar:"" },
       "EX Analog Calc 1":{ en: "", de: "", jp: "-I/O アナログ計算1", es: "", fr: "", ar:"" },
       "EX Analog Calc 2":{ en: "", de: "", jp: "-I/O アナログ計算2", es: "", fr: "", ar:"" },
       "EX Analog Calc 3":{ en: "", de: "", jp: "-I/O アナログ計算3", es: "", fr: "", ar:"" },
       "EX Analog Calc 4":{ en: "", de: "", jp: "-I/O アナログ計算4", es: "", fr: "", ar:"" },
       "EX Analog Calc 5":{ en: "", de: "", jp: "-I/O アナログ計算5", es: "", fr: "", ar:"" },
       "EX Analog Calc 6":{ en: "", de: "", jp: "-I/O アナログ計算6", es: "", fr: "", ar:"" },
       "EX Analog Calc 7":{ en: "", de: "", jp: "-I/O アナログ計算7", es: "", fr: "", ar:"" },
       "EX Digital Input 1":{ en: "", de: "", jp: "I/Oデジタル入力1", es: "", fr: "", ar:"" },
       "EX Digital Input 2":{ en: "", de: "", jp: "I/Oデジタル入力2", es: "", fr: "", ar:"" },
       "EX Digital Input 3":{ en: "", de: "", jp: "I/Oデジタル入力3", es: "", fr: "", ar:"" },
       "EX Digital Input 4":{ en: "", de: "", jp: "I/Oデジタル入力4", es: "", fr: "", ar:"" },
       "EX Digital Input 5":{ en: "", de: "", jp: "I/Oデジタル入力5", es: "", fr: "", ar:"" },
       "EX Digital Input 6":{ en: "", de: "", jp: "I/Oデジタル入力6", es: "", fr: "", ar:"" },
       "EX Digital Input 7":{ en: "", de: "", jp: "I/Oデジタル入力7", es: "", fr: "", ar:"" },
       "EX Digital Input 8":{ en: "", de: "", jp: "I/Oデジタル入力8", es: "", fr: "", ar:"" },
       "EX Digital Frequency 1":{ en: "", de: "", jp: "I/Oデジタル周波数1", es: "", fr: "", ar:"" },
       "Ignition cut":{ en: "", de: "", jp: "IGNカット", es: "", fr: "", ar:"" },
       "Undriven avg. speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
       "Driven avg. speed":{ en: "", de: "", jp: "駆動平均速度", es: "", fr: "", ar:"" },
       "Set Target slip":{ en: "", de: "", jp: "目標スリップ設定", es: "", fr: "", ar:"" },
       "Traction ctrl. power limit":{ en: "", de: "", jp: "TCパワーリミット", es: "", fr: "", ar:"" },
       "Total fuel trim":{ en: "", de: "", jp: "トータル燃料トリム", es: "", fr: "", ar:"" },
       "Total ign comp":{ en: "", de: "", jp: "トータルIGN圧縮", es: "", fr: "", ar:"" },
       "Error code count":{ en: "", de: "", jp: "エラーコード数", es: "", fr: "", ar:"" },
       "Lost sync count":{ en: "", de: "", jp: "非同期化数", es: "", fr: "", ar:"" }
       //Datasources End

   };

function translate(text, language) {
    // Convert numeric language code to string if needed

    var languageString =
        language === 0 ? "en" :
        language === 1 ? "de" :
        language === 2 ? "jp" :
        language === 3 ? "es" :
        language === 4 ? "fr" :
        language === 5 ? "ar" :
        "";
    // Check if the text is defined in translations
    if (translations[text]) {
        // Check if the language is defined for the given text
        var translatedWord = translations[text][languageString];

        // If translation is found and not an empty string, return it
        if (translatedWord !== undefined && translatedWord !== "") {
       // console.log("Translating:", text, "to language:", language, "Result:", translatedWord);
            return translatedWord;
        }
    }

    // If translation is not found or is an empty string, provide the English version
   // console.warn("Translation not found or empty for:", text, "and language:", language);
    return translations[text].en || "Translation not found";
}

