var translations = {
    //Menu Items:
    "Metric": { en: "Metric", de: "Metrisch", jp: "", es: "", fr: "", ar:"" },
    "Imperial": { en: "Imperial", de: "Imperial", jp: "", es: "", fr: "", ar:"" },
    "Analogexplanation": { en: "Enter the Value that should be displayed at 0 V in the field Val.@ 0V and the Value that should be displayed at 5 V in the field Val @5V.The calculated values will be available in the corresponding datasource Analog x Calc", de: "Geben Sie den Wert den Sie bei 0 Volt sehen wollen in das Feld Val.@ 0V, und den Wert den Sie bei 5 Volt sehen wollen in das Feld Val @5V ein.Die Berecheneten Werte werden in den Korrespondierenden Datenquellen Analog x Calc angezeigt.", jp: "", es: "", fr: "", ar:"" },
    "ActiveDashboards": { en: "Active Dashboards", de: "Aktive Dashboards", jp: "", es: "", fr: "", ar:"" },
    "Connect": { en: "Connect", de: "Verbinden", jp: "接続する", es: "", fr: "", ar:"" },
    "Disconnect": { en: "Disconnect", de: "Trennen", jp: "切断する", es: "", fr: "", ar:"" },
    "GPS Connect": { en: "GPS Connect", de: "GPS Verbinden",  jp: "GPS 接続する", es: "", fr: "", ar:"" },
    "GPS Disconnect": { en: "GPS Disconnect", de: "GPS Trennen",  jp: "GPS 切断する", es: "", fr: "", ar:"" },
    "Trip Reset": { en: "Trip Reset", de: "Tages KM reset",  jp: "", es: "", fr: "", ar:"" },
    "Quit": { en: "Quit", de: "Beenden", jp: "終了する", es: "", fr: "", ar:"" },
    "Shutdown": { en: "Shutdown", de: "Herunterfahren",  jp: "シャットダウン", es: "", fr: "", ar:"" },
    "Reboot": { en: "Reboot", de: "Neustart",  jp: "リブート", es: "", fr: "", ar:"" },
    "Language": { en: "Language:", de: "Sprache:",  jp: "言語", es: "Idioma", fr: "Langue", ar:"" },
    "GPS Port": { en: "GPS Port :", de: "GPS Port :",  jp: "", es: "", fr: "", ar:"" },
    "ECU Serial Port": { en: "ECU Serial Port:", de: "ECU Serial Port:",  jp: "", es: "", fr: "", ar:"" },
    "Speed units": { en: "Speed unit:", de: "Geschw. Einh.:",  jp: "", es: "", fr: "", ar:"" },
    "Temp units": { en: "Temp unit:", de: "Temp. Einheit:",  jp: "", es: "", fr: "", ar:"" },
    "Pressure units": { en: "Pressure unit:", de: "Druck Einheit:",  jp: "", es: "", fr: "", ar:"" },
    "ECU Selection": { en: "ECU Selection:", de: "ECU Selektion:",  jp: "", es: "", fr: "", ar:"" },
    "GoPro Variant": { en: "GoPro Variant:", de: "GoPro Variante:",  jp: "", es: "", fr: "", ar:"" },
    "GoPro Pasword": { en: "GoPro Pasword:", de: "GoPro Paswort:",  jp: "", es: "", fr: "", ar:"" },
    "Logfile name": { en: "Logfile name:", de: "Log Datei Name",  jp: "", es: "", fr: "", ar:"" },
    "Odo": { en: "Odo", de: "KM Stand:",  jp: "", es: "", fr: "", ar:"" },
    "Trip": { en: "Trip:                  ", de: "Tages KM Zähler:",  jp: "", es: "", fr: "", ar:"" },
    "Weight": { en: "Weight", de: "Gewicht",  jp: "", es: "", fr: "", ar:"" },
    "Serial Status": { en: "Serial Status", de: "",  jp: "", es: "", fr: "", ar:"" },
    "RPM Smoothing": { en: "RPM Smoothing", de: "Drehzahl Glättung",  jp: "", es: "", fr: "", ar:"" },
    "Speed Smoothing": { en: "Speed Smoothing", de: "Geschw. Glättung",  jp: "", es: "", fr: "", ar:"" },
    "Data Logger": { en: "Data Logger", de: "Daten Logger",  jp: "", es: "", fr: "", ar:"" },
    "GoPro rec": { en: "GoPro rec", de: "GoPro Aufnahme",  jp: "", es: "", fr: "", ar:"" },
    "NMEA Logger": { en: "NMEA Logger", de: "NMEA Logger",  jp: "", es: "", fr: "", ar:"" },
    "(decimal)": { en: "        (decimal)", de: "        (dezimal)",  jp: "          (十進法)", es: "", fr: "", ar:"" },
    "base adress": { en: "      base adress", de: "     start Adresse",  jp: "", es: "", fr: "", ar:"" },
    "Main": { en: "Main", de: "Haupt",  jp: "", es: "", fr: "", ar:"" },
    "Dash Sel.": { en: "Dash Sel.", de: "Dash Ausw.",  jp: "", es: "", fr: "", ar:"" },
    "Sensehat": { en: "Sensehat", de: "Sensehat",  jp: "", es: "", fr: "", ar:"" },
    "Warn / Gear": { en: "Warn/Gear", de: "Warn/Gang",  jp: "", es: "", fr: "", ar:"" },
    "Speedtab": { en: "Speed", de: "Geschw.",  jp: "", es: "", fr: "", ar:"" },
    "Analog": { en: "Analog", de: "Analog",  jp: "", es: "", fr: "", ar:"" },
    "RPM2": { en: "RPM", de: "Drehzahl",  jp: "", es: "", fr: "", ar:"" },
    "EX Board": { en: "EX Board", de: "EX Board",  jp: "", es: "", fr: "", ar:"" },
    "Startup": { en: "Startup", de: "Aufstart",  jp: "", es: "", fr: "", ar:"" },
    "Network": { en: "Network", de: "Netzwerk",  jp: "", es: "", fr: "", ar:"" },
    "Accelerometer": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Compass": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Temperature Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Gyro Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Pressure Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Active Dashboards": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "WaterTemp": { en: "Coolant", de: "Kühlmittel",  jp: "", es: "", fr: "", ar:"" },
    "Boost": { en: "Boost", de: "Ladedruck",  jp: "", es: "", fr: "", ar:"" },
    "Revs": { en: "Max RPM", de: "Max U/min",  jp: "", es: "", fr: "", ar:"" },
    "Knock": { en: "Knock", de: "Klopfen",  jp: "", es: "", fr: "", ar:"" },
    "Lamdamultiply": { en: "Lambda multiply", de: "Lambda Multiplikator",  jp: "", es: "", fr: "", ar:"" },
    "GearCalculation": { en: "Gear Calculation", de: "Gang Berechnung",  jp: "", es: "", fr: "", ar:"" },
    "OFF": { en: "Off", de: "Aus",  jp: "", es: "", fr: "", ar:"" },
    "ON": { en: "On", de: "An",  jp: "", es: "", fr: "", ar:"" },
    "Gear": { en: "Gear", de: "Gang",  jp: "", es: "", fr: "", ar:"" },
    "SpeedCorrection": { en: "Speed Correction %", de: "Geschwindigkeits Korrektur %",  jp: "", es: "", fr: "", ar:"" },
    "Analog description": { en: "Enter the Value that should be displayed at 0V in the field Val.@ 0V and the value that should be displayed at 5 V in the field Val @5V. The calculated values will be availabe in the corresponding datasource Analog x Calc", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Max RPM": { en: "Max RPM", de: "Max Drehzahl",  jp: "", es: "", fr: "", ar:"" },
    "Shift Light": { en: "Shift light", de: "Schalt Blitz",  jp: "", es: "", fr: "", ar:"" },
    "Stage": { en: "stage", de: "Stufe",  jp: "", es: "", fr: "", ar:"" },
    "Voltage divider jumpers": { en: "Voltage divider jumpers", de: "Spannungs Teiler brücke",  jp: "", es: "", fr: "", ar:"" },
    "Temp In.": { en: "Temp. Sensor", de: "Temp. Sensor",  jp: "", es: "", fr: "", ar:"" },
    "Cylinders": { en: "Cylinders", de: "Zylinder",  jp: "", es: "", fr: "", ar:"" },
    "Apply settings": { en: "Apply settings", de: "Einstellungen übernehmen",  jp: "", es: "", fr: "", ar:"" },
    "Apply": { en: "Apply", de: "Übernehmen",  jp: "", es: "", fr: "", ar:"" },
    "Startup daemon": { en: "Startup Daemon", de: "Aufstart Daemon",  jp: "", es: "", fr: "", ar:"" },
    "Can Bitrate": { en: "Can Bitrate", de: "Can Bit Rate",  jp: "", es: "", fr: "", ar:"" },
    "Main Speed Source": { en: "Main Speed Source", de: "Haupt Geschwindigkeits Quelle",  jp: "", es: "", fr: "", ar:"" },
    "Warningtext": { en: "WARNING: DO NOT SELECT ANY START UP DAEMON THAT INCLUDES OBD/OBD2 WHILST TUNING YOUR VEHICLE or working with the ECU/PCM. PowerTune Digital users MUST disable OBD polling when tuning or performing any task related to the ECU/PCM by changing the start up daemon above to a NON OBD/OBD2 option and pressing apply, or disconnecting the dash entirely whilst tuning or working with any vehicle electronics. PowerTune Digital assumes no liability for damage to your vehicle/ECU/PCM if polling OBD data at the same time as another device causes an interruption, or for any other reason. Refer to our warranty at https://www.powertunedigital.com/pages/manual", de: "Warnung : Wählen sie keinen Aufstart daemon aus, der OBD/OBD2 enthält, während Sie ihr Fahrzeug tunen, oder mit dem Steuergerät / PCM arbeiten.PowerTune Digital Nutzer MÜSSEN das OBD Polling während Arbeiten mit dem Steuergerät /PCM abschalten.Sie können einfach einen Aufstart daemon wählen der keine OBD/OBD2 option enthält und dann auf übernehmen drücken, oder das Dash komplett während Arbeiten an der Fahrzeug Elektronik abstecken.PowerTune Digital übernimmt keine Verantwortung für schäden an ihrem Fahrzeug / Steuergerät / PCM / Motor when OBD Daten zur selben Zeit mit einem anderen Gerät gepollt werden und dadurch aussetzer verursachen oder aus anderen Gründen Schäden entstehen. Bitte lesen Sie sich unsere Garantie Bedingungen auf https://www.powertunedigital.com/pages/manual durch.",  jp: "", es: "", fr: "", ar:"" },
    "Scan WIFI": { en: "Scan WIFI", de: "WIFI suchen",  jp: "", es: "", fr: "", ar:"" },
    "WIFI Country": { en: "WIFI country", de: "WIFI LAND",  jp: "", es: "", fr: "", ar:"" },
    "WIFI 1": { en: "WIFI 1", de: "WIFI 1",  jp: "", es: "", fr: "", ar:"" },
    "Password 1": { en: "Password 1", de: "Passwort 1",  jp: "", es: "", fr: "", ar:"" },
    "Connect WIFI": { en: "Connect WIFI", de: "WIFI Verbinden",  jp: "", es: "", fr: "", ar:"" },
    "Update": { en: "Update", de: "Update",  jp: "", es: "", fr: "", ar:"" },
    "Restart daemon": { en: "Restart daemon", de: "Daemon Neustart",  jp: "", es: "", fr: "", ar:"" },
    "Update Tracks": { en: "Update tracks", de: "Strecken Update",  jp: "", es: "", fr: "", ar:"" },
    "Ethernet IP adress": { en: "Ethernet IP adress", de: "Ethernet IP adresse",  jp: "", es: "", fr: "", ar:"" },
    "WLAN IP adress": { en: "WLAN IP adress", de: "WLAN IP adresse",  jp: "", es: "", fr: "", ar:"" },
    "NOT CONNECTED": { en: "NOT CONNECTED", de: "NICHT VERBUNDEN",  jp: "", es: "", fr: "", ar:"" },
    "Damping": { en: "Damping", de: "Dämpfung",  jp: "", es: "", fr: "", ar:"" },
    "Version": { en: "Version", de: "Version",  jp: "", es: "", fr: "", ar:"" },

//Popup submenues 
    "Add": { en: "Add", de: "Einfügen",  jp: "", es: "", fr: "", ar:"" },
    "Square": { en: "Square", de: "Quadrat",  jp: "", es: "", fr: "", ar:"" },
    "Bar": { en: "Bar", de: "Bar",  jp: "", es: "", fr: "", ar:"" },
    "Round": { en: "Round", de: "Rund",  jp: "", es: "", fr: "", ar:"" },
    "Text": { en: "Text", de: "Text",  jp: "", es: "", fr: "", ar:"" },
    "Image": { en: "Image", de: "Bild",  jp: "", es: "", fr: "", ar:"" },
    "State": { en: "State", de: "Status",  jp: "", es: "", fr: "", ar:"" },
    "GIF": { en: "GIF", de: "GIF",  jp: "", es: "", fr: "", ar:"" },
    "Save": { en: "Save", de: "Speichern",  jp: "", es: "", fr: "", ar:"" },
    "Colors": { en: "Colors", de: "Farben",  jp: "", es: "", fr: "", ar:"" },
    "Color": { en: "Color", de: "Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Clear": { en: "Clear", de: "Löschen",  jp: "", es: "", fr: "", ar:"" },
    "Import": { en: "Import", de: "Importieren",  jp: "", es: "", fr: "", ar:"" },
    "Export": { en: "Export", de: "Exportieren",  jp: "", es: "", fr: "", ar:"" },
    "Backround": { en: "Backround", de: "Hintergrund",  jp: "", es: "", fr: "", ar:"" },
    "Close": { en: "Close", de: "Schliessen",  jp: "", es: "", fr: "", ar:"" },
    "Load": { en: "Load", de: "Laden",  jp: "", es: "", fr: "", ar:"" },
    "Cancel": { en: "Cancel", de: "Abbruch",  jp: "", es: "", fr: "", ar:"" },
    "Style": { en: "style", de: "Stil",  jp: "", es: "", fr: "", ar:"" },
    "Extra": { en: "Extra", de: "Extra",  jp: "", es: "", fr: "", ar:"" },
    "None": { en: "None", de: "Kein",  jp: "", es: "", fr: "", ar:"" },
//Square Gauge
    "OK": { en: "OK", de: "OK",  jp: "", es: "", fr: "", ar:"" },
    "Change gauge size": { en: "Change gauge size", de: "Ändere Anzeigen größe",  jp: "", es: "", fr: "", ar:"" },
    "Text font size": { en: "Text font size", de: "Text Schriftart größe",  jp: "", es: "", fr: "", ar:"" },
    "Text font style": { en: "Text font style", de: "Text Schriftart stil",  jp: "", es: "", fr: "", ar:"" },
    "Gauge font size": { en: "Gauge font size", de: "Anzeigen Schriftart größe ",  jp: "", es: "", fr: "", ar:"" },
    "Gauge font style": { en: "Gauge font style", de: "Anzeigen Schriftart stil",  jp: "", es: "", fr: "", ar:"" },
    "Change main value": { en: "Change main value", de: "Ändere haupt wert",  jp: "", es: "", fr: "", ar:"" },
    "Change sec value": { en: "Change sec value", de: "Ändere sekundär wert",  jp: "", es: "", fr: "", ar:"" },
    "Change title": { en: "Change title", de: "Ändere Titel",  jp: "", es: "", fr: "", ar:"" },
    "Set decimal": { en: "Set decimal", de: "Setze dezimal",  jp: "", es: "", fr: "", ar:"" },
    "Set bar gauge max": { en: "Set bar gauge max", de: "Setze Balken Max.",  jp: "", es: "", fr: "", ar:"" },
    "Toggle sec value": { en: "Toggle sec value", de: "Umschalten sekundär Wert",  jp: "", es: "", fr: "", ar:"" },
     "Toggle vertical bar gauge": { en: "Toggle vertical bar gauge", de: "Umschalten vertikaler Balken",  jp: "", es: "", fr: "", ar:"" },
    "Toggle horizontal bar gauge": { en: "Toggle horizontal bar gauge", de: "Umschalten horizontaler Balken",  jp: "", es: "", fr: "", ar:"" },
    "Set min warning": { en: "Set min warnin", de: "Setze min Warnung",  jp: "", es: "", fr: "", ar:"" },
    "Set max warning": { en: "Set max warning", de: "Setze max Warnung",  jp: "", es: "", fr: "", ar:"" },
    "Change unit symbol": { en: "Change unit symbol", de: "Ändere Symboleinheit",  jp: "", es: "", fr: "", ar:"" },
    "remove gauge": { en: "remove gauge", de: "Anzeige löschen",  jp: "", es: "", fr: "", ar:"" },
    "medium": { en: "medium", de: "mittel",  jp: "", es: "", fr: "", ar:"" },
    "small": { en: "small", de: "klein",  jp: "", es: "", fr: "", ar:"" },
    "large": { en: "large", de: "groß",  jp: "", es: "", fr: "", ar:"" },
    "custom": { en: "custom", de: "benutzerdefiniert",  jp: "", es: "", fr: "", ar:"" },
//Round Gauge
    "Start Stop values": { en: "Start Stop value", de: "Start Stop Werte",  jp: "", es: "", fr: "", ar:"" },
    "Test sweep": { en: "Test sweep", de: "Nadel Test",  jp: "", es: "", fr: "", ar:"" },
    "Datasource": { en: "Datasource", de: "Datenquelle",  jp: "", es: "", fr: "", ar:"" },
    "Size and ring": { en: "Size and ring", de: "Größe und Ring",  jp: "", es: "", fr: "", ar:"" },
    "Needle": { en: "Needle", de: "Nadel",  jp: "", es: "", fr: "", ar:"" },
    "Needle trail": { en: "Needle trail", de: "Nadel Schweif",  jp: "", es: "", fr: "", ar:"" },
    "Labels": { en: "Labels", de: "Beschriftungen",  jp: "", es: "", fr: "", ar:"" },
    "Major ticks": { en: "Major ticks", de: "Haupt Ticks",  jp: "", es: "", fr: "", ar:"" },
    "Minor ticks": { en: "Minor ticks", de: "Untergeordnete Ticks",  jp: "", es: "", fr: "", ar:"" },
    "Warnings": { en: "Warnings", de: "Warnungen",  jp: "", es: "", fr: "", ar:"" },
    "Description text": { en: "Description text", de: "Beschreibungs Text",  jp: "", es: "", fr: "", ar:"" },
    "Close menu": { en: "Close menu", de: "Menü schliessen",  jp: "", es: "", fr: "", ar:"" },
    "Gauge size": { en: "Gauge size", de: "Anzeigen Größe",  jp: "", es: "", fr: "", ar:"" },
    "Backround color": { en: "Backround color", de: "Hintergrund Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Outer ring visible": { en: "Outer ring visible", de: "Ring Sichtbarkeit",  jp: "", es: "", fr: "", ar:"" },
    "Needle button visible": { en: "Needle button visible", de: "Knopf Sichtbarkeit",  jp: "", es: "", fr: "", ar:"" },
    "Needle visible": { en: "Needle visible", de: "Nadel Sichtbarkeit",  jp: "", es: "", fr: "", ar:"" },
    "Delete gauge": { en: "Delete gauge", de: "Anzeige löschen",  jp: "", es: "", fr: "", ar:"" },
    "Start value": { en: "Start value", de: "Start Wert",  jp: "", es: "", fr: "", ar:"" },
    "End value": { en: "End value", de: "End Wert",  jp: "", es: "", fr: "", ar:"" },
    "Start angle": { en: "Start angle", de: "Start Winkel",  jp: "", es: "", fr: "", ar:"" },
    "End angle": { en: "End angle", de: "End Winkel",  jp: "", es: "", fr: "", ar:"" },
    "Needle color": { en: "Needle color", de: "Nadel Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Needle lenght": { en: "Needle lenght", de: "Nadel Länge",  jp: "", es: "", fr: "", ar:"" },
    "Needle base width": { en: "Needle base width", de: "Nadel basis breite",  jp: "", es: "", fr: "", ar:"" },
    "Needle tip width": { en: "Needle tip width", de: "Nadel Spitzen breite",  jp: "", es: "", fr: "", ar:"" },
    "Needle offset": { en: "Needle offset", de: "Nadel offset",  jp: "", es: "", fr: "", ar:"" },
    "Outer needle trail": { en: "Outer needle trail", de: "Oberer Nadel Schweif",  jp: "", es: "", fr: "", ar:"" },
    "Middle needle trail": { en: "Middle needle trail", de: "Mittlerer Nadel Schweif",  jp: "", es: "", fr: "", ar:"" },
    "Lower needle trail": { en: "Lower needle trail", de: "Unterer Nadel Schweif",  jp: "", es: "", fr: "", ar:"" },
    "Minor tickmark height": { en: "Minor tickmark heigh", de: "Tick Höhe",  jp: "", es: "", fr: "", ar:"" },
    "Minor tickmark width": { en: "Minor tickmark width", de: "Tick Breite",  jp: "", es: "", fr: "", ar:"" },
    "Minor tickmark steps": { en: "Minor tickmark steps", de: "Tick Schritte",  jp: "", es: "", fr: "", ar:"" },
    "Minor tickmark inset": { en: "Minor tickmark inset", de: "Tick Einsatz",  jp: "", es: "", fr: "", ar:"" },
    "Minor tick active color": { en: "Minor tick active color", de: "Tick aktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Minor tick inactive color": { en: "Minor tick inactive color", de: "Untergeordnete Tick inaktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Major tick steps": { en: "Major tick steps", de: "Haupt Ticks schritte",  jp: "", es: "", fr: "", ar:"" },
    "Major tickmark height": { en: "Major tickmark height", de: "Haupt Ticks Höhe",  jp: "", es: "", fr: "", ar:"" },
    "Major tickmark width": { en: "Major tickmark width", de: "Haupt Ticks Breite",  jp: "", es: "", fr: "", ar:"" },
    "Major tickmark inset": { en: "Major tickmark width", de: "Haupt Ticks Einsatz",  jp: "", es: "", fr: "", ar:"" },
    "Tickmark active color": { en: "Tickmark active color", de: "Ticks aktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Tickmark inactive color": { en: "Tickmark inactive color", de: "Ticks inaktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Major label steps": { en: "Major label steps", de: "Haupt Label Schritte",  jp: "", es: "", fr: "", ar:"" },
    "Label size": { en: "Label size", de: "Label Größe",  jp: "", es: "", fr: "", ar:"" },
    "Label inset": { en: "Label inset", de: "Label Einsatz",  jp: "", es: "", fr: "", ar:"" },
    "Label Font": { en: "Label Font", de: "Label Schriftart",  jp: "", es: "", fr: "", ar:"" },
    "Label active color": { en: "Label active color", de: "Label aktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Label inactive color": { en: "Label inactive color", de: "Label inaktiv Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Low warning trigger": { en: "Low warning trigger", de: "Unterer Warnungs Trigger",  jp: "", es: "", fr: "", ar:"" },
    "High warning trigger": { en: "High warning trigger", de: "Oberer Warnungs Trigger",  jp: "", es: "", fr: "", ar:"" },
    "Red area inset": { en: "Red area inset", de: "Rot Bereich Einsatz",  jp: "", es: "", fr: "", ar:"" },
    "Red start": { en: "Red start", de: "Rot Start",  jp: "", es: "", fr: "", ar:"" },
    "Red area width": { en: "Red area width", de: "Rot Bereich Breite",  jp: "", es: "", fr: "", ar:"" },
    "Horizontal position": { en: "Horizontal position", de: "Horizontale Position",  jp: "", es: "", fr: "", ar:"" },
    "Vertical position": { en: "Vertical position", de: "Vertikale Position",  jp: "", es: "", fr: "", ar:"" },
    "Fontsize": { en: "Fontsize", de: "Schriftgröße",  jp: "", es: "", fr: "", ar:"" },
    "Font": { en: "Font", de: "Schriftart",  jp: "", es: "", fr: "", ar:"" },
    "Font color": { en: "Font color", de: "Schrift Farbe",  jp: "", es: "", fr: "", ar:"" },
    "Display Text": { en: "Display Text", de: "Anzeige Text",  jp: "", es: "", fr: "", ar:"" },
//State GIF
    "Source": { en: "Source", de: "Datenquelle",  jp: "", es: "", fr: "", ar:"" },
    "Trigger": { en: "Trigger", de: "Trigger",  jp: "", es: "", fr: "", ar:"" },
    "Delete image": { en: "Delete image", de: "Bild löschen",  jp: "", es: "", fr: "", ar:"" },
//Text Label
    "Warn value high": { en: "Warn value high", de: "Oberer Warnungs Wert",  jp: "", es: "", fr: "", ar:"" },
    "Warn value low": { en: "Warn value low", de: "Unterer Warnungs Wert",  jp: "", es: "", fr: "", ar:"" },
    "Delete": { en: "Delete", de: "Löschen",  jp: "", es: "", fr: "", ar:"" },
    "Use Datasource": { en: "Use Datasource", de: "Benutze Datenquelle",  jp: "", es: "", fr: "", ar:"" },
//State Picture
    "Image on": { en: "Image on value", de: "Bild an",  jp: "", es: "", fr: "", ar:"" },
    "Image off": { en: "Image off value", de: "Bild aus",  jp: "", es: "", fr: "", ar:"" },




// DATASOURCES Translation, Low priority as i have to find a way to get them to work in a Listmodel ...
    "DRIVESHAFT OFFSET":{ en: "DRIVESHAFT OFFSET", de: "German", jp: "", es: "", fr: "", ar:"" },
    "Average Fuel Economy":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Alternator Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Aux Temp 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Overtemp Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "OilP Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Auto Trans":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "activeboosttable":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "activetunetable":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 0 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 1 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 2 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 3 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 4 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 5 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 6 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 7 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 8 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 9 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 10 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Accel Ped Pos.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Accel. Timmer":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "X accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Y accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Z accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR L.BANK ACTUAL":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR R.BANK ACTUAL":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR L. BANK TARGET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR R. BANK TARGET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Air T.2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Ambi Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Ambi Temp.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Antilag sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Antilag launch":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Rev Limit Sw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Temp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Av. Fuel Economy":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Battery Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Ctrl.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "BOOST OFFSET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Linear boost":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Tp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Wg":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Brake Pedal":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Brake Pressure":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Clutch Sw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Compass":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Calibration select":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Coolant P.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl1 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl2 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl3 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl4 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl5 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl6 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl7 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl8 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Decel Cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Diff Oil T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Dist. To Empty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Dwell":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ECU CPU temp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT highest":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT diff.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Eng. Load":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Exhaust Cam 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Exhaust Cam 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag13":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag14":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag15":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag16":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag17":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag18":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag19":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag20":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag21":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag22":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag23":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag24":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag25":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGN Angle B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGN Angle B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "FSL COMMAND":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "FSL INDEX":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flat Shift":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Correction":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel cor. level":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel tank level":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ethanol":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Cons.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow dif.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow ret.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim long B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim long B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim short B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim short B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear offset":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear Oil Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Generic out 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Altitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Latitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Longitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Time":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Visible Satelites":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gyro X":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Giro Y":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gyro Z":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Handbrake":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Highbeam":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lowbeam":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Homecounter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Idle Val.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inlet Cam 1 angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inlet Cam 2 angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty sec":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj timing.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IAT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ISCV duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knocklevel 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knocklevel 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock restard 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock restard 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock all peak":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock correction":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock last cylinder":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda Target":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Current LAP No":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lap Time":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Best Laptime":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Launch control fuel enrich":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Launch control ign ret.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Leading ign":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "left indicator":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Limp mode":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF 1 Volt":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF 2 Volt":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF activity":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "M.I.L":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Miss count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Master speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Metering Oil Pump":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 Volt 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 Volt 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 CORR R BANK ":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 CORR L BANK":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Odometer":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Oil Pres":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Oil Temp.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PAN VAC":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PIM":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Power":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP Volt.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Pri. Inj pulse width":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rally antilag sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Right Indicator":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM 3STEP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM 2STEP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM HIGHSIDE":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM BOURNOUT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RPM":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Secondary Inj. Pulse width":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Slave speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Steering Wheel Angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Target Boost":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TPS V":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty output active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque red. cut active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque red. level active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TCS OFFSET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TC COMMAND":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Traction Control":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trailing Ign.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Transient throttle active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Transmission Oil T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trigger Counter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Triggers since last home":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trim":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trip meter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Turbo rpm":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Turbo rpm 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Waste gate Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ECT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed difference":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel slip":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed left front":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed right front":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed left rear":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed right rear":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Battery Voltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Boost (abs.)":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Error":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseATemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseBTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseCTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GateDriverTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ControlBoardTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput1FowardSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorTemperature":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TorqueShudder":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput2ReverseSwDigInput2ReverseSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput3BrakeSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput4RegenDisableSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput5IgnSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput6StartSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput7Bool":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput8Bool":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorAngle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ElectricalOutFreq":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DeltaResolverFiltered":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseACurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorSpeed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseBCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseCCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DCBusCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DCBusVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "OutputVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "VABvdVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "VBCvqVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempLF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempRF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempLR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempRR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresLF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresRF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresLR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresRR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Frequency 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Undriven avg. speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Driven avg. speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Set Target slip":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Traction ctrl. power limit":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Total fuel trim":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Total ign comp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Error code count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lost sync count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" }
    //Datasources End

};
function translate(text, language) {
    // Convert numeric language code to string if needed

    var languageString =
        language === 0 ? "en" :
        language === 1 ? "de" :
        language === 2 ? "jp" :
        language === 3 ? "es" :
        language === 4 ? "fr" :
        language === 5 ? "ar" :
        "";
    // Check if the text is defined in translations
    if (translations[text]) {
        // Check if the language is defined for the given text
        var translatedWord = translations[text][languageString];

        // If translation is found and not an empty string, return it
        if (translatedWord !== undefined && translatedWord !== "") {
           console.log("Translating:", text, "to language:", language, "Result:", translatedWord);
            return translatedWord;
        }
    }

    // If translation is not found or is an empty string, provide the English version
   // console.warn("Translation not found or empty for:", text, "and language:", language);
    return translations[text].en || "Translation not found";
}

