var translations = {
    "Connect": { en: "Connect", de: "Verbinden", jp: "接続する", es: "", fr: "", ar:"" },
    "Disconnect": { en: "Disconnect", de: "Trennen", jp: "切断する", es: "", fr: "", ar:"" },
    "GPS Connect": { en: "GPS Connect", de: "GPS Verbinden",  jp: "", es: "", fr: "", ar:"" },
    "GPS Disconnect": { en: "GPS Disconnect", de: "GPS Trennen",  jp: "", es: "", fr: "", ar:"" },
    "Trip Reset": { en: "Trip Reset", de: "Tages KM reset",  jp: "", es: "", fr: "", ar:"" },
    "Quit": { en: "Quit", de: "Beenden", jp: "終了する", es: "", fr: "", ar:"" },
    "Shutdown": { en: "Shutdown", de: "Herunterfahren",  jp: "", es: "", fr: "", ar:"" },
    "Reboot": { en: "Reboot", de: "Neustart",  jp: "", es: "", fr: "", ar:"" },
    "Language": { en: "Language", de: "Sprache",  jp: "", es: "", fr: "", ar:"" },
    "GPS Port": { en: "GPS Port :", de: "GPS Port :",  jp: "", es: "", fr: "", ar:"" },
    "ECU Serial Port": { en: "ECU Serial Port", de: "ECU Serial Port",  jp: "", es: "", fr: "", ar:"" },
    "Speed units": { en: "Speed unit:              ", de: "Geschwindigkeits Einheit:",  jp: "", es: "", fr: "", ar:"" },
    "Temp units": { en: "Temp unit:", de: "Temp. Einheit:",  jp: "", es: "", fr: "", ar:"" },
    "Pressure units": { en: "Pressure unit:", de: "Druck Einheit:",  jp: "", es: "", fr: "", ar:"" },
    "ECU Selection": { en: "ECU Selection", de: "ECU Selektion",  jp: "", es: "", fr: "", ar:"" },
    "GoPro Variant": { en: "GoPro Variant", de: "GoPro Variante",  jp: "", es: "", fr: "", ar:"" },
    "GoPro Pasword": { en: "GoPro Pasword", de: "GoPro Paswort",  jp: "", es: "", fr: "", ar:"" },
    "Logfile name": { en: "Logfile name", de: "Log Datei Name",  jp: "", es: "", fr: "", ar:"" },
    "Odo": { en: "Odo", de: "KM Stand",  jp: "", es: "", fr: "", ar:"" },
    "Trip": { en: "Trip", de: "Tages KM Stand",  jp: "", es: "", fr: "", ar:"" },
    "Weight Kg": { en: "Weight Kg", de: "Gewicht Kg",  jp: "", es: "", fr: "", ar:"" },
    "RPM Smoothing": { en: "RPM Smoothing", de: "Drehzahl Glättung",  jp: "", es: "", fr: "", ar:"" },
    "Speed Smoothing": { en: "Speed Smoothing", de: "Geschwidigkeits Glättung",  jp: "", es: "", fr: "", ar:"" },
    "Data Logger": { en: "Data Logger", de: "Daten Logger",  jp: "", es: "", fr: "", ar:"" },
    "GoPro rec": { en: "GoPro rec", de: "GoPro Aufnahme",  jp: "", es: "", fr: "", ar:"" },
    "NMEA Logger": { en: "NMEA Logger", de: "NMEA Logger",  jp: "", es: "", fr: "", ar:"" },
    "CAN Extender start adress (decimal)": { en: "CAN Extender start adress (decimal)", de: "CAN Extender start adresse (dezimal)",  jp: "", es: "", fr: "", ar:"" },
    "Shiftligt CAN start adress (decimal)": { en: "Shiftligt CAN start adress (decimal)", de: "Schalt Licht CAN start adresse (dezimal)",  jp: "", es: "", fr: "", ar:"" },
    "Main": { en: "Main", de: "Haupt",  jp: "", es: "", fr: "", ar:"" },
    "Dash Sel.": { en: "Dash Sel.", de: "Dash Auswahl.",  jp: "", es: "", fr: "", ar:"" },
    "Sensehat": { en: "Sensehat", de: "Sensehat",  jp: "", es: "", fr: "", ar:"" },
    "Warn / Gear": { en: "Warn / Gear", de: "Warn / Gang",  jp: "", es: "", fr: "", ar:"" },
    "Speed": { en: "Speed", de: "Geschwindigkeit",  jp: "", es: "", fr: "", ar:"" },
    "Analog": { en: "Analog", de: "Analog",  jp: "", es: "", fr: "", ar:"" },
    "RPM": { en: "RPM", de: "Drehzahl",  jp: "", es: "", fr: "", ar:"" },
    "EX Board": { en: "EX Board", de: "EX Board",  jp: "", es: "", fr: "", ar:"" },
    "Startup": { en: "Startup", de: "Aufstart",  jp: "", es: "", fr: "", ar:"" },
    "Network": { en: "Network", de: "Netzwerk",  jp: "", es: "", fr: "", ar:"" },
    "Accelerometer": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Compass": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Temperature Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Gyro Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Pressure Sensor": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Active Dashboards": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Water Temp": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Boost": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Revs": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Knock": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Lambda multiply": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Gear Calculation": { en: "", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Off": { en: "Off", de: "Aus",  jp: "", es: "", fr: "", ar:"" },
    "On": { en: "ON", de: "an",  jp: "", es: "", fr: "", ar:"" },
    "Gear": { en: "Gear", de: "Gang",  jp: "", es: "", fr: "", ar:"" },
    "Speed Correction %": { en: "Speed Correction %", de: "Geschwindigkeits Korrektur %",  jp: "", es: "", fr: "", ar:"" },
    "Analog description": { en: "Enter the Value that should be displayed at 0V in the field Val.@ 0V and the value that should be displayed at 5 V in the field Val @5V. The calculated values will be availabe in the corresponding datasource Analog x Calc", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Max RPM": { en: "Max RPM", de: "Max Drehzahl",  jp: "", es: "", fr: "", ar:"" },
    "Shift Light": { en: "Shift Light", de: "Schalt Licht",  jp: "", es: "", fr: "", ar:"" },
    "Voltage divider jumpers": { en: "Voltage divider jumpers", de: "Spannungs Teiler jumper",  jp: "", es: "", fr: "", ar:"" },
    "Cylinders": { en: "Cylinders", de: "Zylinder",  jp: "", es: "", fr: "", ar:"" },
    "Apply settings": { en: "Apply settings", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Apply": { en: "Apply", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Startup Daemon": { en: "Startup Daemon", de: "Startup Daemon",  jp: "", es: "", fr: "", ar:"" },
    "Can Bitrate": { en: "Can Bitrate", de: "Can Bit Rate",  jp: "", es: "", fr: "", ar:"" },
    "Main Speed Source": { en: "Main Speed Source", de: "Haupt Geschwindigkeits Quelle",  jp: "", es: "", fr: "", ar:"" },
    "Startup warning text": { en: "DO NOT SELECT ANY START UP DAEMON THAT INCLUDES OBD/OBD2 WHILST TUNING YOUR VEHICLE or working with the ECU/PCM. PowerTune Digital users MUST disable OBD polling when tuning or performing any task related to the ECU/PCM by changing the start up daemon above to a NON OBD/OBD2 option and pressing apply, or disconnecting the dash entirely whilst tuning or working with any vehicle electronics. PowerTune Digital assumes no liability for damage to your vehicle/ECU/PCM if polling OBD data at the same time as another device causes an interruption, or for any other reason. Refer to our warranty at https://www.powertunedigital.com/pages/manual", de: "",  jp: "", es: "", fr: "", ar:"" },
    "Scan WIFI": { en: "Scan WIFI", de: "WIFI suchen",  jp: "", es: "", fr: "", ar:"" },
    "WIFI country": { en: "WIFI country", de: "WIFI LAND",  jp: "", es: "", fr: "", ar:"" },
    "WIFI 1": { en: "WIFI 1", de: "WIFI 1",  jp: "", es: "", fr: "", ar:"" },
    "Password 1": { en: "Password 1", de: "Passwort 1",  jp: "", es: "", fr: "", ar:"" },
    "Connect WIFI": { en: "Connect WIFI", de: "WIFI Verbinden",  jp: "", es: "", fr: "", ar:"" },
    "Update": { en: "Update", de: "Update",  jp: "", es: "", fr: "", ar:"" },
    "Restart daemon": { en: "Restart daemon", de: "Daemon Neustart",  jp: "", es: "", fr: "", ar:"" },
    "Update tracks": { en: "Update tracks", de: "Strecken Update",  jp: "", es: "", fr: "", ar:"" },
    "Ethernet IP adress": { en: "Ethernet IP adress", de: "Ethernet IP adresse",  jp: "", es: "", fr: "", ar:"" },
    "WLAN IP adress": { en: "WLAN IP adress", de: "WLAN IP adresse",  jp: "", es: "", fr: "", ar:"" },
    "NOT CONNECTED": { en: "NOT CONNECTED", de: "NICHT VERBUNDEN",  jp: "", es: "", fr: "", ar:"" },

 // DATASOURCES
    "DRIVESHAFT OFFSET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Average Fuel Economy":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Alternator Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Aux Temp 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Overtemp Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "OilP Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Auto Trans":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "activeboosttable":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "activetunetable":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 0 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 1 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 2 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 3 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 4 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 5 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 6 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 7 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 8 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 9 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Analog 10 Calc":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Accel Ped Pos.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Accel. Timmer":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "X accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Y accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Z accel.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR L.BANK ACTUAL":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR R.BANK ACTUAL":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR L. BANK TARGET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR R. BANK TARGET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "AFR CYL 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AFR CYL 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Air T.2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Ambi Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Ambi Temp.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Antilag sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Antilag launch":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Calc4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Rev Limit Sw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "AUX Temp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Av. Fuel Economy":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Battery Light":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Ctrl.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "BOOST OFFSET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Linear boost":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Tp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Boost Wg":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Brake Pedal":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Brake Pressure":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Clutch Sw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Compass":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Calibration select":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Coolant P.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl1 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl2 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl3 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl4 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl5 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl6 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl7 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Cyl8 O2 Corr.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Decel Cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "Diff Oil T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
     "DigitalInput 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Dist. To Empty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Dwell":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ECU CPU temp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT 12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT highest":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EGT diff.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Eng. Load":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Exhaust Cam 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Exhaust Cam 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag13":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag14":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag15":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag16":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag17":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag18":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag19":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag20":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag21":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag22":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag23":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag24":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flag25":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGN Angle B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGN Angle B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "FSL COMMAND":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "FSL INDEX":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Flat Shift":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Correction":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel cor. level":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel tank level":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ethanol":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Cons.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow dif.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel flow ret.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim long B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim long B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim short B1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Fuel trim short B2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear offset":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear Caluclation":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gear Oil Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Generic out 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Altitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Latitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Longitude":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Time":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GPS Visible Satelites":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gyro X":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Giro Y":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Gyro Z":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Handbrake":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Highbeam":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lowbeam":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Homecounter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Idle Val.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inlet Cam 1 angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inlet Cam 2 angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj. Duty sec":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Inj timing.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IAT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ISCV duty":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knocklevel 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knocklevel 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock restard 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock restard 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock all peak":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock correction":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Knock last cylinder":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lambda Target":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Current LAP No":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lap Time":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Best Laptime":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Launch control fuel enrich":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Launch control ign ret.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Leading ign":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "left indicator":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Limp mode":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF 1 Volt":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF 2 Volt":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAF activity":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "M.I.L":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Miss count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Master speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Metering Oil Pump":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "NOS sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 Volt 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 Volt 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 CORR R BANK ":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "O2 CORR L BANK":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Odometer":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Oil Pres":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Oil Temp.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PAN VAC":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PIM":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Power":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "MAP Volt.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Pri. Inj pulse width":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rally antilag sw.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Right Indicator":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM 3STEP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM 2STEP":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM HIGHSIDE":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "REV LIM BOURNOUT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RPM":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Rorary Trimpot 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Secondary Inj. Pulse width":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Slave speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Sensor 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Steering Wheel Angle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Target Boost":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TPS V":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Timed duty output active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque red. cut active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Torque red. level active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TCS OFFSET":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TC COMMAND":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Traction Control":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trailing Ign.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Transient throttle active":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Transmission Oil T.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trigger Counter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Triggers since last home":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trim":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Trip meter":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Turbo rpm":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Turbo rpm 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 9":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 10":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 11":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "User Channel 12":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Waste gate Pres.":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ECT":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed difference":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel slip":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed left front":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed right front":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed left rear":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Wheel speed right rear":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Battery Voltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Boost (abs.)":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Error":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseATemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseBTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "IGBTPhaseCTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "GateDriverTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ControlBoardTemp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput1FowardSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "RtdTemp5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorTemperature":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TorqueShudder":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput2ReverseSwDigInput2ReverseSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput3BrakeSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput4RegenDisableSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput5IgnSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput6StartSw":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput7Bool":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DigInput8Bool":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorAngle":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "ElectricalOutFreq":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DeltaResolverFiltered":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseACurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EMotorSpeed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseBCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "PhaseCCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DCBusCurrent":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "DCBusVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "OutputVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "VABvdVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "VBCvqVoltage":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempLF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempRF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempLR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TiretempRR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresLF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresRF":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresLR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "TirepresRR":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX AnalogInput 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 0":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Analog Calc 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 2":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 3":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 4":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 5":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 6":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 7":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Input 8":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "EX Digital Frequency 1":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Ignition cut":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Undriven avg. speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Driven avg. speed":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Set Target slip":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Traction ctrl. power limit":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Total fuel trim":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Total ign comp":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Error code count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" },
    "Lost sync count":{ en: "", de: "", jp: "", es: "", fr: "", ar:"" }



    //Datasources End

};

function translate(text, language) {
    // Convert numeric language code to string if needed
    var languageString = language === 0 ? "en" : (language === 1 ? "de" : (language === 2 ? "jp" : ""));

    // Check if the text is defined in translations
    if (translations[text]) {
        // Check if the language is defined for the given text
        var translatedWord = translations[text][languageString];

        // If translation is found, return it
        if (translatedWord !== undefined) {
            console.log("Translating:", text, "to language:", language, "Result:", translatedWord);
            return translatedWord;
        }
    }

    // If translation is not found, provide a default value or handle the situation accordingly
    console.warn("Translation not found for:", text, "and language:", language);
    return "Translation not found";
}
