name: Test builds on armv7

on:  
  push:    
    branches: [ gh-builds ]

jobs:   
  build:    
    runs-on: ubuntu-20.04    
    env:      
      DOCKER_IMAGE: "powertune"
      DOCKER_TARGET_PLATFORM: linux/arm/v7 
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1              
 
    - name: Build test image
      if: success()      
      run: |        
        docker build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:latest \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.buildx-version }} \
        .github/workflows/