name: Generate Doxygen documentation

on:
  push:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
