name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate QML and JavaScript files
        uses: liri-infra/qmllint-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
